package domain

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"regexp"
	"strings"
	"time"
)

// Organization represents a Voxis organization (tenant).
type Organization struct {
	ID              string
	Name            string
	Slug            string
	Settings        map[string]any
	EncryptionKeyID string // Vault KEK reference
	Tier            string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// LiveRecordingRetentionPolicy controls automatic deletion of live recording audio.
type LiveRecordingRetentionPolicy struct {
	Enabled         bool
	Days            int
	EffectiveAt     *time.Time
	ApplyToExisting bool
	UpdatedAt       *time.Time
	UpdatedBy       string
}

// LiveRecordingRetentionPreview reports the immediate impact of a proposed policy.
type LiveRecordingRetentionPreview struct {
	ImmediateDeleteCount   int64
	OldestCompletedAt      *time.Time
	ProspectiveEffectiveAt *time.Time
}

// Validate checks whether the retention policy is internally consistent.
func (p LiveRecordingRetentionPolicy) Validate() error {
	if p.Days == 0 {
		if !p.Enabled {
			return nil
		}
		return fmt.Errorf("live recording retention days must be between 1 and 30: %w", ErrInvalidInput)
	}
	if p.Days < 1 || p.Days > 30 {
		return fmt.Errorf("live recording retention days must be between 1 and 30: %w", ErrInvalidInput)
	}
	return nil
}

// NewOrganization creates a new organization with a generated slug.
func NewOrganization(name string) (*Organization, error) {
	if name == "" {
		return nil, errors.New("organization name cannot be empty")
	}

	slug := generateSlug(name)

	return &Organization{
		// ID is generated by database (uuid_generate_v4)
		Name:     name,
		Slug:     slug,
		Settings: make(map[string]any),
		Tier:     "free",
	}, nil
}

// NewPersonalOrganization creates an org for a user based on their email.
func NewPersonalOrganization(email string) (*Organization, error) {
	if email == "" {
		return nil, errors.New("email cannot be empty")
	}

	// Extract name from email (before @)
	parts := strings.Split(email, "@")
	name := parts[0] + "'s Workspace"

	return NewOrganization(name)
}

// generateSlug creates a URL-safe slug from name with random suffix.
func generateSlug(name string) string {
	// Lowercase and replace non-alphanumeric with hyphens
	slug := strings.ToLower(name)
	slug = regexp.MustCompile(`[^a-z0-9]+`).ReplaceAllString(slug, "-")
	slug = strings.Trim(slug, "-")

	// Truncate if too long (leaving room for suffix)
	if len(slug) > 80 {
		slug = slug[:80]
	}

	// Add random suffix to avoid collisions
	suffix := make([]byte, 4)
	_, _ = rand.Read(suffix) //nolint:errcheck // crypto/rand.Read only fails on catastrophic system failure
	slug = slug + "-" + hex.EncodeToString(suffix)

	return slug
}

// SetEncryptionKeyID sets the Vault key reference.
func (o *Organization) SetEncryptionKeyID(keyID string) {
	o.EncryptionKeyID = keyID
	o.UpdatedAt = time.Now()
}

// Clone returns a deep copy of the organization.
func (o *Organization) Clone() *Organization {
	settings := make(map[string]any)
	for k, v := range o.Settings {
		settings[k] = v
	}
	return &Organization{
		ID:              o.ID,
		Name:            o.Name,
		Slug:            o.Slug,
		Settings:        settings,
		EncryptionKeyID: o.EncryptionKeyID,
		Tier:            o.Tier,
		CreatedAt:       o.CreatedAt,
		UpdatedAt:       o.UpdatedAt,
	}
}
