package export

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/gomutex/godocx"
	"github.com/gomutex/godocx/docx"
	"github.com/voxis/backend/internal/port"
)

// FormatDOCX generates a DOCX document from export data using godocx.
func (f *Formatter) FormatDOCX(data *port.ExportData) ([]byte, error) {
	doc, err := godocx.NewDocument()
	if err != nil {
		return nil, fmt.Errorf("creating DOCX document: %w", err)
	}

	if _, err := doc.AddHeading(data.Title, 0); err != nil {
		return nil, fmt.Errorf("adding title: %w", err)
	}

	addDOCXMetadata(doc, data)

	if err := addDOCXTranscript(doc, data); err != nil {
		return nil, err
	}
	if err := addDOCXSummaries(doc, data); err != nil {
		return nil, err
	}

	doc.AddEmptyParagraph()
	footerPara := doc.AddEmptyParagraph()
	footerPara.AddText("Generated by Voxis").Italic(true).Color("808080")

	var buf bytes.Buffer
	if err := doc.Write(&buf); err != nil {
		return nil, fmt.Errorf("writing DOCX: %w", err)
	}

	return buf.Bytes(), nil
}

// addDOCXMetadata adds metadata lines to the document.
func addDOCXMetadata(doc *docx.RootDoc, data *port.ExportData) {
	var metaLines []string
	if len(data.Languages) > 0 {
		metaLines = append(metaLines, fmt.Sprintf("Language: %s", strings.Join(data.Languages, ", ")))
	}
	if data.Duration > 0 {
		metaLines = append(metaLines, fmt.Sprintf("Duration: %s", formatTimestamp(data.Duration)))
	}
	if data.SpeakerCount > 0 {
		metaLines = append(metaLines, fmt.Sprintf("Speakers: %d", data.SpeakerCount))
	}
	if data.WordCount > 0 {
		metaLines = append(metaLines, fmt.Sprintf("Words: %d", data.WordCount))
	}
	if !data.CreatedAt.IsZero() {
		metaLines = append(metaLines, fmt.Sprintf("Created: %s", data.CreatedAt.Format("2006-01-02 15:04")))
	}
	if data.CompletedAt != nil {
		metaLines = append(metaLines, fmt.Sprintf("Completed: %s", data.CompletedAt.Format("2006-01-02 15:04")))
	}

	for _, line := range metaLines {
		doc.AddParagraph(line)
	}
}

// addDOCXTranscript adds the transcript section (utterances, full text, or placeholder).
// When summaries are present but no transcript content exists (summary-only export),
// the transcript section is omitted entirely to avoid a confusing placeholder.
func addDOCXTranscript(doc *docx.RootDoc, data *port.ExportData) error {
	switch {
	case len(data.Utterances) > 0:
		if _, err := doc.AddHeading("Transcript", 1); err != nil {
			return fmt.Errorf("adding transcript heading: %w", err)
		}
		for _, u := range data.Utterances {
			name := speakerName(u.Speaker, data.SpeakerMap)
			timestamp := fmt.Sprintf("[%s - %s]", formatTimestamp(u.Start), formatTimestamp(u.End))

			speakerPara := doc.AddEmptyParagraph()
			speakerPara.AddText(fmt.Sprintf("%s %s", name, timestamp)).Bold(true)

			if resolvedText := u.ResolvedText(); resolvedText != "" {
				doc.AddParagraph(resolvedText)
			}
		}
	case data.FullTranscript != "":
		if _, err := doc.AddHeading("Transcript", 1); err != nil {
			return fmt.Errorf("adding transcript heading: %w", err)
		}
		doc.AddParagraph(data.FullTranscript)
	default:
		// Summary-only exports: omit transcript section when summaries exist.
		if len(data.Summaries) > 0 {
			return nil
		}
		p := doc.AddEmptyParagraph()
		p.AddText("No transcript content.").Italic(true).Color("808080")
	}
	return nil
}

// addDOCXSummaries adds summary sections to the document.
func addDOCXSummaries(doc *docx.RootDoc, data *port.ExportData) error {
	for _, s := range data.Summaries {
		label := summaryTypeLabels[s.Type]
		if label == "" {
			label = s.Type
		}

		if _, err := doc.AddHeading(label, 1); err != nil {
			return fmt.Errorf("adding summary heading: %w", err)
		}

		if s.Content != "" {
			doc.AddParagraph(s.Content)
		}
	}
	return nil
}
