// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    (SELECT COUNT(*) FROM media m WHERE m.organization_id = $1 AND m.status != 'deleted') AS total_media,
    ((SELECT COUNT(*) FROM media m WHERE m.organization_id = $1 AND m.status IN ('pending', 'encrypting')) +
     (SELECT COUNT(*) FROM transcriptions t WHERE t.organization_id = $1 AND t.status IN ('pending', 'submitted'))
    )::bigint AS processing_count,
    (SELECT COUNT(*) FROM media m WHERE m.organization_id = $1 AND m.status IN ('pending', 'encrypting')) AS encrypting_count,
    (SELECT COUNT(*) FROM transcriptions t WHERE t.organization_id = $1 AND t.status IN ('pending', 'submitted')) AS transcribing_count,
    (SELECT COUNT(*) FROM transcriptions t WHERE t.organization_id = $1 AND t.status = 'completed') AS completed_transcriptions,
    (SELECT COUNT(*) FROM transcriptions t WHERE t.organization_id = $1 AND t.status = 'completed'
       AND t.completed_at >= date_trunc('month', NOW() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC') AS completed_this_month,
    (SELECT COUNT(*) FROM transcriptions t WHERE t.organization_id = $1 AND t.status = 'completed'
       AND t.completed_at >= (date_trunc('month', NOW() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC') - INTERVAL '1 month'
       AND t.completed_at < date_trunc('month', NOW() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC') AS completed_last_month,
    COALESCE((SELECT SUM(t.duration_seconds) FROM transcriptions t WHERE t.organization_id = $1 AND t.status = 'completed'
       AND t.completed_at >= date_trunc('month', NOW() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'), 0)::double precision AS seconds_this_month,
    COALESCE((SELECT MAX(t.completed_at) FROM transcriptions t WHERE t.organization_id = $1 AND t.status = 'completed'),
       '1970-01-01 00:00:00+00'::timestamptz)::timestamptz AS last_completed_at
`

type GetDashboardStatsRow struct {
	TotalMedia              int64     `db:"total_media" json:"total_media"`
	ProcessingCount         int64     `db:"processing_count" json:"processing_count"`
	EncryptingCount         int64     `db:"encrypting_count" json:"encrypting_count"`
	TranscribingCount       int64     `db:"transcribing_count" json:"transcribing_count"`
	CompletedTranscriptions int64     `db:"completed_transcriptions" json:"completed_transcriptions"`
	CompletedThisMonth      int64     `db:"completed_this_month" json:"completed_this_month"`
	CompletedLastMonth      int64     `db:"completed_last_month" json:"completed_last_month"`
	SecondsThisMonth        float64   `db:"seconds_this_month" json:"seconds_this_month"`
	LastCompletedAt         time.Time `db:"last_completed_at" json:"last_completed_at"`
}

func (q *Queries) GetDashboardStats(ctx context.Context, organizationID pgtype.UUID) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats, organizationID)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.TotalMedia,
		&i.ProcessingCount,
		&i.EncryptingCount,
		&i.TranscribingCount,
		&i.CompletedTranscriptions,
		&i.CompletedThisMonth,
		&i.CompletedLastMonth,
		&i.SecondsThisMonth,
		&i.LastCompletedAt,
	)
	return i, err
}
