// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMCPCollectionItem = `-- name: AddMCPCollectionItem :exec
INSERT INTO mcp_collection_items (collection_id, transcription_id)
SELECT c.id, t.id
FROM mcp_collections c
JOIN transcriptions t ON t.id = $1
  AND t.organization_id = c.organization_id AND t.status != 'deleted'
WHERE c.organization_id = $2 AND c.id = $3
ON CONFLICT (collection_id, transcription_id) DO NOTHING
`

type AddMCPCollectionItemParams struct {
	TranscriptionID pgtype.UUID `db:"transcription_id" json:"transcription_id"`
	OrganizationID  pgtype.UUID `db:"organization_id" json:"organization_id"`
	CollectionID    pgtype.UUID `db:"collection_id" json:"collection_id"`
}

func (q *Queries) AddMCPCollectionItem(ctx context.Context, arg AddMCPCollectionItemParams) error {
	_, err := q.db.Exec(ctx, addMCPCollectionItem, arg.TranscriptionID, arg.OrganizationID, arg.CollectionID)
	return err
}

const countSearchAllEntities = `-- name: CountSearchAllEntities :one
SELECT COUNT(*) FROM media m
WHERE m.organization_id = $1
  AND m.status != 'deleted'
  AND (
    m.filename ILIKE '%' || replace(replace(replace($2::text, '\', '\\'), '%', '\%'), '_', '\_') || '%' ESCAPE '\'
    OR COALESCE(m.title, '') ILIKE '%' || replace(replace(replace($2::text, '\', '\\'), '%', '\%'), '_', '\_') || '%' ESCAPE '\'
    OR COALESCE(m.description, '') ILIKE '%' || replace(replace(replace($2::text, '\', '\\'), '%', '\%'), '_', '\_') || '%' ESCAPE '\'
  )
`

type CountSearchAllEntitiesParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	Search         string      `db:"search" json:"search"`
}

func (q *Queries) CountSearchAllEntities(ctx context.Context, arg CountSearchAllEntitiesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchAllEntities, arg.OrganizationID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMCPCollection = `-- name: CreateMCPCollection :one
INSERT INTO mcp_collections (organization_id, name, description, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id::text, organization_id::text, name, description, created_by, created_at, updated_at
`

type CreateMCPCollectionParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	Name           string      `db:"name" json:"name"`
	Description    string      `db:"description" json:"description"`
	CreatedBy      string      `db:"created_by" json:"created_by"`
}

type CreateMCPCollectionRow struct {
	ID             string    `db:"id" json:"id"`
	OrganizationID string    `db:"organization_id" json:"organization_id"`
	Name           string    `db:"name" json:"name"`
	Description    string    `db:"description" json:"description"`
	CreatedBy      string    `db:"created_by" json:"created_by"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateMCPCollection(ctx context.Context, arg CreateMCPCollectionParams) (CreateMCPCollectionRow, error) {
	row := q.db.QueryRow(ctx, createMCPCollection,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
	)
	var i CreateMCPCollectionRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMCPCollection = `-- name: GetMCPCollection :one
SELECT c.id::text AS id, c.organization_id::text AS organization_id, c.name, c.description,
  c.created_by, c.created_at, c.updated_at, COUNT(i.transcription_id)::int AS item_count
FROM mcp_collections c
LEFT JOIN mcp_collection_items i ON i.collection_id = c.id
WHERE c.organization_id = $1 AND c.id = $2
GROUP BY c.id
`

type GetMCPCollectionParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	CollectionID   pgtype.UUID `db:"collection_id" json:"collection_id"`
}

type GetMCPCollectionRow struct {
	ID             string    `db:"id" json:"id"`
	OrganizationID string    `db:"organization_id" json:"organization_id"`
	Name           string    `db:"name" json:"name"`
	Description    string    `db:"description" json:"description"`
	CreatedBy      string    `db:"created_by" json:"created_by"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
	ItemCount      int32     `db:"item_count" json:"item_count"`
}

func (q *Queries) GetMCPCollection(ctx context.Context, arg GetMCPCollectionParams) (GetMCPCollectionRow, error) {
	row := q.db.QueryRow(ctx, getMCPCollection, arg.OrganizationID, arg.CollectionID)
	var i GetMCPCollectionRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ItemCount,
	)
	return i, err
}

const listMCPCollectionItems = `-- name: ListMCPCollectionItems :many
SELECT i.collection_id::text AS collection_id, i.transcription_id::text AS transcription_id, i.added_at
FROM mcp_collection_items i
JOIN mcp_collections c ON c.id = i.collection_id
JOIN transcriptions t ON t.id = i.transcription_id
WHERE c.organization_id = $1 AND i.collection_id = $2
  AND t.organization_id = c.organization_id AND t.status != 'deleted'
ORDER BY i.added_at DESC
LIMIT $4 OFFSET $3
`

type ListMCPCollectionItemsParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	CollectionID   pgtype.UUID `db:"collection_id" json:"collection_id"`
	OffsetVal      int32       `db:"offset_val" json:"offset_val"`
	LimitVal       int32       `db:"limit_val" json:"limit_val"`
}

type ListMCPCollectionItemsRow struct {
	CollectionID    string    `db:"collection_id" json:"collection_id"`
	TranscriptionID string    `db:"transcription_id" json:"transcription_id"`
	AddedAt         time.Time `db:"added_at" json:"added_at"`
}

func (q *Queries) ListMCPCollectionItems(ctx context.Context, arg ListMCPCollectionItemsParams) ([]ListMCPCollectionItemsRow, error) {
	rows, err := q.db.Query(ctx, listMCPCollectionItems,
		arg.OrganizationID,
		arg.CollectionID,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMCPCollectionItemsRow
	for rows.Next() {
		var i ListMCPCollectionItemsRow
		if err := rows.Scan(&i.CollectionID, &i.TranscriptionID, &i.AddedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPCollections = `-- name: ListMCPCollections :many
SELECT c.id::text AS id, c.organization_id::text AS organization_id, c.name, c.description,
  c.created_by, c.created_at, c.updated_at, COUNT(i.transcription_id)::int AS item_count
FROM mcp_collections c
LEFT JOIN mcp_collection_items i ON i.collection_id = c.id
WHERE c.organization_id = $1
GROUP BY c.id
ORDER BY c.created_at DESC
LIMIT $3 OFFSET $2
`

type ListMCPCollectionsParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	OffsetVal      int32       `db:"offset_val" json:"offset_val"`
	LimitVal       int32       `db:"limit_val" json:"limit_val"`
}

type ListMCPCollectionsRow struct {
	ID             string    `db:"id" json:"id"`
	OrganizationID string    `db:"organization_id" json:"organization_id"`
	Name           string    `db:"name" json:"name"`
	Description    string    `db:"description" json:"description"`
	CreatedBy      string    `db:"created_by" json:"created_by"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
	ItemCount      int32     `db:"item_count" json:"item_count"`
}

func (q *Queries) ListMCPCollections(ctx context.Context, arg ListMCPCollectionsParams) ([]ListMCPCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listMCPCollections, arg.OrganizationID, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMCPCollectionsRow
	for rows.Next() {
		var i ListMCPCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptionsWithoutSummaries = `-- name: ListTranscriptionsWithoutSummaries :many
SELECT
  t.id::text AS id,
  'media'::text AS source_type,
  t.status,
  t.word_count,
  t.speaker_count,
  t.duration_seconds,
  t.created_at,
  COALESCE(NULLIF(TRIM(m.title), ''), m.filename, '') AS display_name,
  COALESCE(m.description, '') AS description
FROM transcriptions t
JOIN media m ON t.media_id = m.id AND m.status != 'deleted'
WHERE t.organization_id = $1
  AND t.status = 'completed'
  AND NOT EXISTS (
    SELECT 1 FROM summaries s
    WHERE s.transcription_id = t.id AND s.status = 'completed'
      AND ($2::text = '' OR s.summary_type = $2)
  )
ORDER BY t.created_at DESC
LIMIT $4 OFFSET $3
`

type ListTranscriptionsWithoutSummariesParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	SummaryType    string      `db:"summary_type" json:"summary_type"`
	OffsetVal      int32       `db:"offset_val" json:"offset_val"`
	LimitVal       int32       `db:"limit_val" json:"limit_val"`
}

type ListTranscriptionsWithoutSummariesRow struct {
	ID              string    `db:"id" json:"id"`
	SourceType      string    `db:"source_type" json:"source_type"`
	Status          string    `db:"status" json:"status"`
	WordCount       int32     `db:"word_count" json:"word_count"`
	SpeakerCount    int32     `db:"speaker_count" json:"speaker_count"`
	DurationSeconds float64   `db:"duration_seconds" json:"duration_seconds"`
	CreatedAt       time.Time `db:"created_at" json:"created_at"`
	DisplayName     string    `db:"display_name" json:"display_name"`
	Description     string    `db:"description" json:"description"`
}

func (q *Queries) ListTranscriptionsWithoutSummaries(ctx context.Context, arg ListTranscriptionsWithoutSummariesParams) ([]ListTranscriptionsWithoutSummariesRow, error) {
	rows, err := q.db.Query(ctx, listTranscriptionsWithoutSummaries,
		arg.OrganizationID,
		arg.SummaryType,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTranscriptionsWithoutSummariesRow
	for rows.Next() {
		var i ListTranscriptionsWithoutSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceType,
			&i.Status,
			&i.WordCount,
			&i.SpeakerCount,
			&i.DurationSeconds,
			&i.CreatedAt,
			&i.DisplayName,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMCPCollectionItem = `-- name: RemoveMCPCollectionItem :exec
DELETE FROM mcp_collection_items i
USING mcp_collections c
WHERE i.collection_id = c.id
  AND c.organization_id = $1
  AND i.collection_id = $2
  AND i.transcription_id = $3
`

type RemoveMCPCollectionItemParams struct {
	OrganizationID  pgtype.UUID `db:"organization_id" json:"organization_id"`
	CollectionID    pgtype.UUID `db:"collection_id" json:"collection_id"`
	TranscriptionID pgtype.UUID `db:"transcription_id" json:"transcription_id"`
}

func (q *Queries) RemoveMCPCollectionItem(ctx context.Context, arg RemoveMCPCollectionItemParams) error {
	_, err := q.db.Exec(ctx, removeMCPCollectionItem, arg.OrganizationID, arg.CollectionID, arg.TranscriptionID)
	return err
}

const searchAllEntities = `-- name: SearchAllEntities :many
SELECT
  m.id::text AS id,
  'media'::text AS entity_type,
  COALESCE(NULLIF(TRIM(m.title), ''), m.filename, '') AS title,
  COALESCE(m.description, '') AS description,
  m.filename,
  m.status,
  m.created_at,
  COALESCE((
    SELECT t.id::text FROM transcriptions t
    WHERE t.media_id = m.id AND t.organization_id = m.organization_id AND t.status = 'completed'
    ORDER BY t.completed_at DESC NULLS LAST LIMIT 1
  ), '') AS latest_transcription_id
FROM media m
WHERE m.organization_id = $1
  AND m.status != 'deleted'
  AND (
    m.filename ILIKE '%' || replace(replace(replace($2::text, '\', '\\'), '%', '\%'), '_', '\_') || '%' ESCAPE '\'
    OR COALESCE(m.title, '') ILIKE '%' || replace(replace(replace($2::text, '\', '\\'), '%', '\%'), '_', '\_') || '%' ESCAPE '\'
    OR COALESCE(m.description, '') ILIKE '%' || replace(replace(replace($2::text, '\', '\\'), '%', '\%'), '_', '\_') || '%' ESCAPE '\'
  )
ORDER BY m.created_at DESC
LIMIT $4 OFFSET $3
`

type SearchAllEntitiesParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	Search         string      `db:"search" json:"search"`
	OffsetVal      int32       `db:"offset_val" json:"offset_val"`
	LimitVal       int32       `db:"limit_val" json:"limit_val"`
}

type SearchAllEntitiesRow struct {
	ID                    string      `db:"id" json:"id"`
	EntityType            string      `db:"entity_type" json:"entity_type"`
	Title                 string      `db:"title" json:"title"`
	Description           string      `db:"description" json:"description"`
	Filename              string      `db:"filename" json:"filename"`
	Status                string      `db:"status" json:"status"`
	CreatedAt             time.Time   `db:"created_at" json:"created_at"`
	LatestTranscriptionID interface{} `db:"latest_transcription_id" json:"latest_transcription_id"`
}

func (q *Queries) SearchAllEntities(ctx context.Context, arg SearchAllEntitiesParams) ([]SearchAllEntitiesRow, error) {
	rows, err := q.db.Query(ctx, searchAllEntities,
		arg.OrganizationID,
		arg.Search,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAllEntitiesRow
	for rows.Next() {
		var i SearchAllEntitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Title,
			&i.Description,
			&i.Filename,
			&i.Status,
			&i.CreatedAt,
			&i.LatestTranscriptionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
