// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMediaByOrganization = `-- name: CountMediaByOrganization :one
SELECT COUNT(*) FROM media
WHERE organization_id = $1 AND status != 'deleted'
`

func (q *Queries) CountMediaByOrganization(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMediaByOrganization, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchMediaByOrganization = `-- name: CountSearchMediaByOrganization :one
SELECT COUNT(*) FROM media
WHERE organization_id = $1
  AND status != 'deleted'
  AND ($2::text = '' OR (
    filename ILIKE '%' || replace(replace(replace($2, '\', '\\'), '%', '\%'), '_', '\_') || '%' ESCAPE '\'
    OR COALESCE(title, '') ILIKE '%' || replace(replace(replace($2, '\', '\\'), '%', '\%'), '_', '\_') || '%' ESCAPE '\'
    OR COALESCE(description, '') ILIKE '%' || replace(replace(replace($2, '\', '\\'), '%', '\%'), '_', '\_') || '%' ESCAPE '\'
  ))
  AND ($3::text = '' OR status = $3)
`

type CountSearchMediaByOrganizationParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	SearchQuery    string      `db:"search_query" json:"search_query"`
	StatusFilter   string      `db:"status_filter" json:"status_filter"`
}

func (q *Queries) CountSearchMediaByOrganization(ctx context.Context, arg CountSearchMediaByOrganizationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchMediaByOrganization, arg.OrganizationID, arg.SearchQuery, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
    organization_id, created_by, filename, content_type, size, duration, status, scan_status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, organization_id, created_by, filename, content_type, size, duration, status, scan_status, storage_key, wrapped_dek, wrapping_nonce, encryption_algo, chunk_size, chunk_count, title, description, file_hash, audio_metadata, audio_deleted_at, created_at, updated_at
`

type CreateMediaParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	CreatedBy      pgtype.Text `db:"created_by" json:"created_by"`
	Filename       string      `db:"filename" json:"filename"`
	ContentType    string      `db:"content_type" json:"content_type"`
	Size           int64       `db:"size" json:"size"`
	Duration       float64     `db:"duration" json:"duration"`
	Status         string      `db:"status" json:"status"`
	ScanStatus     string      `db:"scan_status" json:"scan_status"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.OrganizationID,
		arg.CreatedBy,
		arg.Filename,
		arg.ContentType,
		arg.Size,
		arg.Duration,
		arg.Status,
		arg.ScanStatus,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.Duration,
		&i.Status,
		&i.ScanStatus,
		&i.StorageKey,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.EncryptionAlgo,
		&i.ChunkSize,
		&i.ChunkCount,
		&i.Title,
		&i.Description,
		&i.FileHash,
		&i.AudioMetadata,
		&i.AudioDeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMediaRecordingChunks = `-- name: DeleteMediaRecordingChunks :exec
DELETE FROM recording_chunks
WHERE session_id IN (SELECT id FROM recording_sessions WHERE media_id = $1)
`

func (q *Queries) DeleteMediaRecordingChunks(ctx context.Context, mediaID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMediaRecordingChunks, mediaID)
	return err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, organization_id, created_by, filename, content_type, size, duration, status, scan_status, storage_key, wrapped_dek, wrapping_nonce, encryption_algo, chunk_size, chunk_count, title, description, file_hash, audio_metadata, audio_deleted_at, created_at, updated_at FROM media WHERE id = $1
`

func (q *Queries) GetMediaByID(ctx context.Context, id pgtype.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.Duration,
		&i.Status,
		&i.ScanStatus,
		&i.StorageKey,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.EncryptionAlgo,
		&i.ChunkSize,
		&i.ChunkCount,
		&i.Title,
		&i.Description,
		&i.FileHash,
		&i.AudioMetadata,
		&i.AudioDeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMediaByOrganization = `-- name: ListMediaByOrganization :many
SELECT id, organization_id, created_by, filename, content_type, size, duration, status, scan_status, storage_key, wrapped_dek, wrapping_nonce, encryption_algo, chunk_size, chunk_count, title, description, file_hash, audio_metadata, audio_deleted_at, created_at, updated_at FROM media
WHERE organization_id = $1 AND status != 'deleted'
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListMediaByOrganizationParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	OffsetVal      int32       `db:"offset_val" json:"offset_val"`
	LimitVal       int32       `db:"limit_val" json:"limit_val"`
}

func (q *Queries) ListMediaByOrganization(ctx context.Context, arg ListMediaByOrganizationParams) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMediaByOrganization, arg.OrganizationID, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Filename,
			&i.ContentType,
			&i.Size,
			&i.Duration,
			&i.Status,
			&i.ScanStatus,
			&i.StorageKey,
			&i.WrappedDek,
			&i.WrappingNonce,
			&i.EncryptionAlgo,
			&i.ChunkSize,
			&i.ChunkCount,
			&i.Title,
			&i.Description,
			&i.FileHash,
			&i.AudioMetadata,
			&i.AudioDeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaRecordingChunkKeysForPurge = `-- name: ListMediaRecordingChunkKeysForPurge :many
SELECT c.storage_key FROM recording_chunks c
JOIN recording_sessions s ON s.id = c.session_id
WHERE s.media_id = $1
ORDER BY c.storage_key
LIMIT 5000
`

func (q *Queries) ListMediaRecordingChunkKeysForPurge(ctx context.Context, mediaID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listMediaRecordingChunkKeysForPurge, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMediaForPurge = `-- name: LockMediaForPurge :one

SELECT id FROM media WHERE id = $1 FOR UPDATE
`

// The media purge runs in one transaction. Rows are locked parent-first
// (media, then its transcriptions) so a worker that share-locks a
// transcription before writing segment ciphertext waits for the purge and
// then sees status 'deleted'.
func (q *Queries) LockMediaForPurge(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockMediaForPurge, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const lockMediaTranscriptionsForPurge = `-- name: LockMediaTranscriptionsForPurge :many
SELECT id FROM transcriptions WHERE media_id = $1 ORDER BY id FOR UPDATE
`

func (q *Queries) LockMediaTranscriptionsForPurge(ctx context.Context, mediaID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, lockMediaTranscriptionsForPurge, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMediaAudioDeleted = `-- name: MarkMediaAudioDeleted :one
UPDATE media
SET storage_key = NULL,
    wrapped_dek = NULL,
    wrapping_nonce = NULL,
    encryption_algo = NULL,
    chunk_size = 0,
    chunk_count = 0,
    file_hash = NULL,
    audio_metadata = NULL,
    audio_deleted_at = COALESCE(audio_deleted_at, $1),
    updated_at = NOW()
WHERE id = $2 AND storage_key = $3
RETURNING id, organization_id, created_by, filename, content_type, size, duration, status, scan_status, storage_key, wrapped_dek, wrapping_nonce, encryption_algo, chunk_size, chunk_count, title, description, file_hash, audio_metadata, audio_deleted_at, created_at, updated_at
`

type MarkMediaAudioDeletedParams struct {
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	ID         pgtype.UUID        `db:"id" json:"id"`
	StorageKey pgtype.Text        `db:"storage_key" json:"storage_key"`
}

func (q *Queries) MarkMediaAudioDeleted(ctx context.Context, arg MarkMediaAudioDeletedParams) (Medium, error) {
	row := q.db.QueryRow(ctx, markMediaAudioDeleted, arg.DeletedAt, arg.ID, arg.StorageKey)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.Duration,
		&i.Status,
		&i.ScanStatus,
		&i.StorageKey,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.EncryptionAlgo,
		&i.ChunkSize,
		&i.ChunkCount,
		&i.Title,
		&i.Description,
		&i.FileHash,
		&i.AudioMetadata,
		&i.AudioDeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const purgeMediaRow = `-- name: PurgeMediaRow :exec

UPDATE media SET
    status = 'deleted',
    filename = '',
    title = NULL,
    description = NULL,
    file_hash = NULL,
    audio_metadata = NULL,
    storage_key = NULL,
    wrapped_dek = NULL,
    wrapping_nonce = NULL,
    encryption_algo = NULL,
    chunk_size = 0,
    chunk_count = 0,
    audio_deleted_at = COALESCE(audio_deleted_at, NOW())
WHERE id = $1
`

// PurgeMediaRow keeps a content-free tombstone: status, size, duration and
// timestamps stay for activity and admin counts; every name, hash, and key
// reference goes.
func (q *Queries) PurgeMediaRow(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, purgeMediaRow, id)
	return err
}

const scrubMediaRecordingSessions = `-- name: ScrubMediaRecordingSessions :exec
UPDATE recording_sessions SET microphone_label = NULL WHERE media_id = $1
`

func (q *Queries) ScrubMediaRecordingSessions(ctx context.Context, mediaID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, scrubMediaRecordingSessions, mediaID)
	return err
}

const searchMediaByOrganization = `-- name: SearchMediaByOrganization :many
SELECT id, organization_id, created_by, filename, content_type, size, duration, status, scan_status, storage_key, wrapped_dek, wrapping_nonce, encryption_algo, chunk_size, chunk_count, title, description, file_hash, audio_metadata, audio_deleted_at, created_at, updated_at FROM media
WHERE organization_id = $1
  AND status != 'deleted'
  AND ($2::text = '' OR (
    filename ILIKE '%' || replace(replace(replace($2, '\', '\\'), '%', '\%'), '_', '\_') || '%' ESCAPE '\'
    OR COALESCE(title, '') ILIKE '%' || replace(replace(replace($2, '\', '\\'), '%', '\%'), '_', '\_') || '%' ESCAPE '\'
    OR COALESCE(description, '') ILIKE '%' || replace(replace(replace($2, '\', '\\'), '%', '\%'), '_', '\_') || '%' ESCAPE '\'
  ))
  AND ($3::text = '' OR status = $3)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type SearchMediaByOrganizationParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	SearchQuery    string      `db:"search_query" json:"search_query"`
	StatusFilter   string      `db:"status_filter" json:"status_filter"`
	OffsetVal      int32       `db:"offset_val" json:"offset_val"`
	LimitVal       int32       `db:"limit_val" json:"limit_val"`
}

func (q *Queries) SearchMediaByOrganization(ctx context.Context, arg SearchMediaByOrganizationParams) ([]Medium, error) {
	rows, err := q.db.Query(ctx, searchMediaByOrganization,
		arg.OrganizationID,
		arg.SearchQuery,
		arg.StatusFilter,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Filename,
			&i.ContentType,
			&i.Size,
			&i.Duration,
			&i.Status,
			&i.ScanStatus,
			&i.StorageKey,
			&i.WrappedDek,
			&i.WrappingNonce,
			&i.EncryptionAlgo,
			&i.ChunkSize,
			&i.ChunkCount,
			&i.Title,
			&i.Description,
			&i.FileHash,
			&i.AudioMetadata,
			&i.AudioDeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMedia = `-- name: SoftDeleteMedia :exec
UPDATE media SET status = 'deleted' WHERE id = $1
`

func (q *Queries) SoftDeleteMedia(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteMedia, id)
	return err
}

const updateMediaDuration = `-- name: UpdateMediaDuration :one
UPDATE media SET duration = $1 WHERE id = $2 RETURNING id, organization_id, created_by, filename, content_type, size, duration, status, scan_status, storage_key, wrapped_dek, wrapping_nonce, encryption_algo, chunk_size, chunk_count, title, description, file_hash, audio_metadata, audio_deleted_at, created_at, updated_at
`

type UpdateMediaDurationParams struct {
	Duration float64     `db:"duration" json:"duration"`
	ID       pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateMediaDuration(ctx context.Context, arg UpdateMediaDurationParams) (Medium, error) {
	row := q.db.QueryRow(ctx, updateMediaDuration, arg.Duration, arg.ID)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.Duration,
		&i.Status,
		&i.ScanStatus,
		&i.StorageKey,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.EncryptionAlgo,
		&i.ChunkSize,
		&i.ChunkCount,
		&i.Title,
		&i.Description,
		&i.FileHash,
		&i.AudioMetadata,
		&i.AudioDeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMediaEncryption = `-- name: UpdateMediaEncryption :one
UPDATE media SET
    storage_key = $1,
    wrapped_dek = $2,
    wrapping_nonce = $3,
    encryption_algo = $4,
    chunk_size = $5,
    chunk_count = $6,
    status = $7
WHERE id = $8
RETURNING id, organization_id, created_by, filename, content_type, size, duration, status, scan_status, storage_key, wrapped_dek, wrapping_nonce, encryption_algo, chunk_size, chunk_count, title, description, file_hash, audio_metadata, audio_deleted_at, created_at, updated_at
`

type UpdateMediaEncryptionParams struct {
	StorageKey     pgtype.Text `db:"storage_key" json:"storage_key"`
	WrappedDek     []byte      `db:"wrapped_dek" json:"wrapped_dek"`
	WrappingNonce  []byte      `db:"wrapping_nonce" json:"wrapping_nonce"`
	EncryptionAlgo pgtype.Text `db:"encryption_algo" json:"encryption_algo"`
	ChunkSize      int32       `db:"chunk_size" json:"chunk_size"`
	ChunkCount     int32       `db:"chunk_count" json:"chunk_count"`
	Status         string      `db:"status" json:"status"`
	ID             pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateMediaEncryption(ctx context.Context, arg UpdateMediaEncryptionParams) (Medium, error) {
	row := q.db.QueryRow(ctx, updateMediaEncryption,
		arg.StorageKey,
		arg.WrappedDek,
		arg.WrappingNonce,
		arg.EncryptionAlgo,
		arg.ChunkSize,
		arg.ChunkCount,
		arg.Status,
		arg.ID,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.Duration,
		&i.Status,
		&i.ScanStatus,
		&i.StorageKey,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.EncryptionAlgo,
		&i.ChunkSize,
		&i.ChunkCount,
		&i.Title,
		&i.Description,
		&i.FileHash,
		&i.AudioMetadata,
		&i.AudioDeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMediaForensics = `-- name: UpdateMediaForensics :one
UPDATE media SET file_hash = $1, audio_metadata = $2
WHERE id = $3
RETURNING id, organization_id, created_by, filename, content_type, size, duration, status, scan_status, storage_key, wrapped_dek, wrapping_nonce, encryption_algo, chunk_size, chunk_count, title, description, file_hash, audio_metadata, audio_deleted_at, created_at, updated_at
`

type UpdateMediaForensicsParams struct {
	FileHash      pgtype.Text `db:"file_hash" json:"file_hash"`
	AudioMetadata []byte      `db:"audio_metadata" json:"audio_metadata"`
	ID            pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateMediaForensics(ctx context.Context, arg UpdateMediaForensicsParams) (Medium, error) {
	row := q.db.QueryRow(ctx, updateMediaForensics, arg.FileHash, arg.AudioMetadata, arg.ID)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.Duration,
		&i.Status,
		&i.ScanStatus,
		&i.StorageKey,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.EncryptionAlgo,
		&i.ChunkSize,
		&i.ChunkCount,
		&i.Title,
		&i.Description,
		&i.FileHash,
		&i.AudioMetadata,
		&i.AudioDeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMediaMetadata = `-- name: UpdateMediaMetadata :one
UPDATE media SET
    title = CASE WHEN $1::boolean THEN $2 ELSE title END,
    description = CASE WHEN $3::boolean THEN $4 ELSE description END
WHERE id = $5
RETURNING id, organization_id, created_by, filename, content_type, size, duration, status, scan_status, storage_key, wrapped_dek, wrapping_nonce, encryption_algo, chunk_size, chunk_count, title, description, file_hash, audio_metadata, audio_deleted_at, created_at, updated_at
`

type UpdateMediaMetadataParams struct {
	SetTitle       bool        `db:"set_title" json:"set_title"`
	Title          pgtype.Text `db:"title" json:"title"`
	SetDescription bool        `db:"set_description" json:"set_description"`
	Description    pgtype.Text `db:"description" json:"description"`
	ID             pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateMediaMetadata(ctx context.Context, arg UpdateMediaMetadataParams) (Medium, error) {
	row := q.db.QueryRow(ctx, updateMediaMetadata,
		arg.SetTitle,
		arg.Title,
		arg.SetDescription,
		arg.Description,
		arg.ID,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.Duration,
		&i.Status,
		&i.ScanStatus,
		&i.StorageKey,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.EncryptionAlgo,
		&i.ChunkSize,
		&i.ChunkCount,
		&i.Title,
		&i.Description,
		&i.FileHash,
		&i.AudioMetadata,
		&i.AudioDeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMediaScanStatus = `-- name: UpdateMediaScanStatus :exec
UPDATE media SET scan_status = $1, updated_at = NOW() WHERE id = $2
`

type UpdateMediaScanStatusParams struct {
	ScanStatus string      `db:"scan_status" json:"scan_status"`
	ID         pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateMediaScanStatus(ctx context.Context, arg UpdateMediaScanStatusParams) error {
	_, err := q.db.Exec(ctx, updateMediaScanStatus, arg.ScanStatus, arg.ID)
	return err
}

const updateMediaStatus = `-- name: UpdateMediaStatus :one
UPDATE media SET status = $1 WHERE id = $2 RETURNING id, organization_id, created_by, filename, content_type, size, duration, status, scan_status, storage_key, wrapped_dek, wrapping_nonce, encryption_algo, chunk_size, chunk_count, title, description, file_hash, audio_metadata, audio_deleted_at, created_at, updated_at
`

type UpdateMediaStatusParams struct {
	Status string      `db:"status" json:"status"`
	ID     pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateMediaStatus(ctx context.Context, arg UpdateMediaStatusParams) (Medium, error) {
	row := q.db.QueryRow(ctx, updateMediaStatus, arg.Status, arg.ID)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.Duration,
		&i.Status,
		&i.ScanStatus,
		&i.StorageKey,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.EncryptionAlgo,
		&i.ChunkSize,
		&i.ChunkCount,
		&i.Title,
		&i.Description,
		&i.FileHash,
		&i.AudioMetadata,
		&i.AudioDeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
