// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	OrganizationID pgtype.UUID        `db:"organization_id" json:"organization_id"`
	CreatedBy      string             `db:"created_by" json:"created_by"`
	Name           string             `db:"name" json:"name"`
	KeyPrefix      string             `db:"key_prefix" json:"key_prefix"`
	KeyHash        string             `db:"key_hash" json:"key_hash"`
	Scopes         []string           `db:"scopes" json:"scopes"`
	LastUsedAt     pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt      pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt      time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time          `db:"updated_at" json:"updated_at"`
}

type AppRecordingRetentionPolicy struct {
	ID              bool               `db:"id" json:"id"`
	Enabled         bool               `db:"enabled" json:"enabled"`
	RetentionDays   int16              `db:"retention_days" json:"retention_days"`
	EffectiveAt     pgtype.Timestamptz `db:"effective_at" json:"effective_at"`
	ApplyToExisting bool               `db:"apply_to_existing" json:"apply_to_existing"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy       pgtype.Text        `db:"updated_by" json:"updated_by"`
}

type AppStorageQuotaPolicy struct {
	ID                      bool               `db:"id" json:"id"`
	Enabled                 bool               `db:"enabled" json:"enabled"`
	DefaultLimitBytes       int64              `db:"default_limit_bytes" json:"default_limit_bytes"`
	WarningThresholdPercent int16              `db:"warning_threshold_percent" json:"warning_threshold_percent"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy               pgtype.Text        `db:"updated_by" json:"updated_by"`
}

type LlmPromptOverride struct {
	Key               string    `db:"key" json:"key"`
	SystemInstruction string    `db:"system_instruction" json:"system_instruction"`
	UserPrompt        string    `db:"user_prompt" json:"user_prompt"`
	Model             string    `db:"model" json:"model"`
	UpdatedAt         time.Time `db:"updated_at" json:"updated_at"`
	UpdatedBy         string    `db:"updated_by" json:"updated_by"`
}

type McpCollection struct {
	ID             pgtype.UUID `db:"id" json:"id"`
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	Name           string      `db:"name" json:"name"`
	Description    string      `db:"description" json:"description"`
	CreatedBy      string      `db:"created_by" json:"created_by"`
	CreatedAt      time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time   `db:"updated_at" json:"updated_at"`
}

type McpCollectionItem struct {
	CollectionID    pgtype.UUID `db:"collection_id" json:"collection_id"`
	TranscriptionID pgtype.UUID `db:"transcription_id" json:"transcription_id"`
	AddedAt         time.Time   `db:"added_at" json:"added_at"`
}

type Medium struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	OrganizationID pgtype.UUID        `db:"organization_id" json:"organization_id"`
	CreatedBy      pgtype.Text        `db:"created_by" json:"created_by"`
	Filename       string             `db:"filename" json:"filename"`
	ContentType    string             `db:"content_type" json:"content_type"`
	Size           int64              `db:"size" json:"size"`
	Duration       float64            `db:"duration" json:"duration"`
	Status         string             `db:"status" json:"status"`
	ScanStatus     string             `db:"scan_status" json:"scan_status"`
	StorageKey     pgtype.Text        `db:"storage_key" json:"storage_key"`
	WrappedDek     []byte             `db:"wrapped_dek" json:"wrapped_dek"`
	WrappingNonce  []byte             `db:"wrapping_nonce" json:"wrapping_nonce"`
	EncryptionAlgo pgtype.Text        `db:"encryption_algo" json:"encryption_algo"`
	ChunkSize      int32              `db:"chunk_size" json:"chunk_size"`
	ChunkCount     int32              `db:"chunk_count" json:"chunk_count"`
	Title          pgtype.Text        `db:"title" json:"title"`
	Description    pgtype.Text        `db:"description" json:"description"`
	FileHash       pgtype.Text        `db:"file_hash" json:"file_hash"`
	AudioMetadata  []byte             `db:"audio_metadata" json:"audio_metadata"`
	AudioDeletedAt pgtype.Timestamptz `db:"audio_deleted_at" json:"audio_deleted_at"`
	CreatedAt      time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time          `db:"updated_at" json:"updated_at"`
}

type Organization struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	Name            string      `db:"name" json:"name"`
	Slug            string      `db:"slug" json:"slug"`
	Settings        []byte      `db:"settings" json:"settings"`
	EncryptionKeyID pgtype.Text `db:"encryption_key_id" json:"encryption_key_id"`
	Tier            string      `db:"tier" json:"tier"`
	CreatedAt       time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time   `db:"updated_at" json:"updated_at"`
}

type RecordingChunk struct {
	ID             pgtype.UUID `db:"id" json:"id"`
	SessionID      pgtype.UUID `db:"session_id" json:"session_id"`
	Seq            int32       `db:"seq" json:"seq"`
	StorageKey     string      `db:"storage_key" json:"storage_key"`
	WrappedDek     []byte      `db:"wrapped_dek" json:"wrapped_dek"`
	WrappingNonce  []byte      `db:"wrapping_nonce" json:"wrapping_nonce"`
	EncryptionAlgo string      `db:"encryption_algo" json:"encryption_algo"`
	ChunkSize      int32       `db:"chunk_size" json:"chunk_size"`
	ChunkCount     int32       `db:"chunk_count" json:"chunk_count"`
	PlaintextSize  int64       `db:"plaintext_size" json:"plaintext_size"`
	Checksum       string      `db:"checksum" json:"checksum"`
	UploadedAt     time.Time   `db:"uploaded_at" json:"uploaded_at"`
}

type RecordingSession struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	OrganizationID  pgtype.UUID        `db:"organization_id" json:"organization_id"`
	UserID          string             `db:"user_id" json:"user_id"`
	Status          string             `db:"status" json:"status"`
	MimeType        string             `db:"mime_type" json:"mime_type"`
	MicrophoneLabel pgtype.Text        `db:"microphone_label" json:"microphone_label"`
	CaptureSource   string             `db:"capture_source" json:"capture_source"`
	MediaID         pgtype.UUID        `db:"media_id" json:"media_id"`
	TotalDuration   float64            `db:"total_duration" json:"total_duration"`
	LastChunkAt     pgtype.Timestamptz `db:"last_chunk_at" json:"last_chunk_at"`
	LastActivityAt  time.Time          `db:"last_activity_at" json:"last_activity_at"`
	CreatedAt       time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time          `db:"updated_at" json:"updated_at"`
	CompletedAt     pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

type Summary struct {
	ID                             pgtype.UUID        `db:"id" json:"id"`
	OrganizationID                 pgtype.UUID        `db:"organization_id" json:"organization_id"`
	TranscriptionID                pgtype.UUID        `db:"transcription_id" json:"transcription_id"`
	SummaryType                    string             `db:"summary_type" json:"summary_type"`
	SummaryProfile                 string             `db:"summary_profile" json:"summary_profile"`
	Status                         string             `db:"status" json:"status"`
	ContentEncrypted               []byte             `db:"content_encrypted" json:"content_encrypted"`
	ContentNonce                   []byte             `db:"content_nonce" json:"content_nonce"`
	WrappedDek                     []byte             `db:"wrapped_dek" json:"wrapped_dek"`
	WrappingNonce                  []byte             `db:"wrapping_nonce" json:"wrapping_nonce"`
	WordCount                      int32              `db:"word_count" json:"word_count"`
	PromptTokens                   int32              `db:"prompt_tokens" json:"prompt_tokens"`
	CompletionTokens               int32              `db:"completion_tokens" json:"completion_tokens"`
	ThinkingTokens                 int32              `db:"thinking_tokens" json:"thinking_tokens"`
	ErrorMessage                   pgtype.Text        `db:"error_message" json:"error_message"`
	HighStakes                     bool               `db:"high_stakes" json:"high_stakes"`
	ReviewStatus                   string             `db:"review_status" json:"review_status"`
	ReviewFindingsEncrypted        []byte             `db:"review_findings_encrypted" json:"review_findings_encrypted"`
	ReviewFindingsNonce            []byte             `db:"review_findings_nonce" json:"review_findings_nonce"`
	ReviewWrappedDek               []byte             `db:"review_wrapped_dek" json:"review_wrapped_dek"`
	ReviewWrappingNonce            []byte             `db:"review_wrapping_nonce" json:"review_wrapping_nonce"`
	ExtractionEncrypted            []byte             `db:"extraction_encrypted" json:"extraction_encrypted"`
	ExtractionNonce                []byte             `db:"extraction_nonce" json:"extraction_nonce"`
	ExtractionWrappedDek           []byte             `db:"extraction_wrapped_dek" json:"extraction_wrapped_dek"`
	ExtractionWrappingNonce        []byte             `db:"extraction_wrapping_nonce" json:"extraction_wrapping_nonce"`
	PromptVersion                  pgtype.Text        `db:"prompt_version" json:"prompt_version"`
	Model                          pgtype.Text        `db:"model" json:"model"`
	ModelMetadata                  []byte             `db:"model_metadata" json:"model_metadata"`
	EndpointLocation               pgtype.Text        `db:"endpoint_location" json:"endpoint_location"`
	SourceVersion                  pgtype.Text        `db:"source_version" json:"source_version"`
	SourceHash                     pgtype.Text        `db:"source_hash" json:"source_hash"`
	StructuredContentCiphertext    []byte             `db:"structured_content_ciphertext" json:"structured_content_ciphertext"`
	StructuredContentNonce         []byte             `db:"structured_content_nonce" json:"structured_content_nonce"`
	StructuredContentWrappedDek    []byte             `db:"structured_content_wrapped_dek" json:"structured_content_wrapped_dek"`
	StructuredContentWrappingNonce []byte             `db:"structured_content_wrapping_nonce" json:"structured_content_wrapping_nonce"`
	StructuredSchemaVersion        pgtype.Text        `db:"structured_schema_version" json:"structured_schema_version"`
	DegradationCodes               []string           `db:"degradation_codes" json:"degradation_codes"`
	CreatedAt                      time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt                      time.Time          `db:"updated_at" json:"updated_at"`
	CompletedAt                    pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

type Transcription struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	OrganizationID        pgtype.UUID        `db:"organization_id" json:"organization_id"`
	MediaID               pgtype.UUID        `db:"media_id" json:"media_id"`
	Provider              string             `db:"provider" json:"provider"`
	SpeechmaticsJobID     pgtype.Text        `db:"speechmatics_job_id" json:"speechmatics_job_id"`
	SpeechmaticsDeletedAt pgtype.Timestamptz `db:"speechmatics_deleted_at" json:"speechmatics_deleted_at"`
	Status                string             `db:"status" json:"status"`
	Languages             []string           `db:"languages" json:"languages"`
	Diarization           bool               `db:"diarization" json:"diarization"`
	ExpectedSpeakers      pgtype.Int4        `db:"expected_speakers" json:"expected_speakers"`
	VocabularyPacks       []string           `db:"vocabulary_packs" json:"vocabulary_packs"`
	EnhanceAudio          bool               `db:"enhance_audio" json:"enhance_audio"`
	PreprocessorUsed      pgtype.Text        `db:"preprocessor_used" json:"preprocessor_used"`
	ContentEncrypted      []byte             `db:"content_encrypted" json:"content_encrypted"`
	ContentNonce          []byte             `db:"content_nonce" json:"content_nonce"`
	WrappedDek            []byte             `db:"wrapped_dek" json:"wrapped_dek"`
	WrappingNonce         []byte             `db:"wrapping_nonce" json:"wrapping_nonce"`
	SpeakerCount          int32              `db:"speaker_count" json:"speaker_count"`
	WordCount             int32              `db:"word_count" json:"word_count"`
	DurationSeconds       float64            `db:"duration_seconds" json:"duration_seconds"`
	ErrorMessage          pgtype.Text        `db:"error_message" json:"error_message"`
	CreatedAt             time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt             time.Time          `db:"updated_at" json:"updated_at"`
	CompletedAt           pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

type TranscriptionSegment struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	TranscriptionID       pgtype.UUID        `db:"transcription_id" json:"transcription_id"`
	SegmentIndex          int32              `db:"segment_index" json:"segment_index"`
	StartOffsetSec        float64            `db:"start_offset_sec" json:"start_offset_sec"`
	EndOffsetSec          float64            `db:"end_offset_sec" json:"end_offset_sec"`
	SpeechmaticsJobID     pgtype.Text        `db:"speechmatics_job_id" json:"speechmatics_job_id"`
	SpeechmaticsDeletedAt pgtype.Timestamptz `db:"speechmatics_deleted_at" json:"speechmatics_deleted_at"`
	Status                string             `db:"status" json:"status"`
	ContentEncrypted      []byte             `db:"content_encrypted" json:"content_encrypted"`
	ContentNonce          []byte             `db:"content_nonce" json:"content_nonce"`
	WrappedDek            []byte             `db:"wrapped_dek" json:"wrapped_dek"`
	WrappingNonce         []byte             `db:"wrapping_nonce" json:"wrapping_nonce"`
	SpeakerCount          int32              `db:"speaker_count" json:"speaker_count"`
	WordCount             int32              `db:"word_count" json:"word_count"`
	DurationSeconds       float64            `db:"duration_seconds" json:"duration_seconds"`
	ErrorMessage          pgtype.Text        `db:"error_message" json:"error_message"`
	CreatedAt             time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt             time.Time          `db:"updated_at" json:"updated_at"`
	CompletedAt           pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

type User struct {
	ID              string      `db:"id" json:"id"`
	OrganizationID  pgtype.UUID `db:"organization_id" json:"organization_id"`
	Email           string      `db:"email" json:"email"`
	NormalizedEmail pgtype.Text `db:"normalized_email" json:"normalized_email"`
	Name            string      `db:"name" json:"name"`
	Role            string      `db:"role" json:"role"`
	Preferences     []byte      `db:"preferences" json:"preferences"`
	CreatedAt       time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time   `db:"updated_at" json:"updated_at"`
}

type UserStorageAllocation struct {
	ID                 string             `db:"id" json:"id"`
	OrganizationID     pgtype.UUID        `db:"organization_id" json:"organization_id"`
	UserID             string             `db:"user_id" json:"user_id"`
	Kind               string             `db:"kind" json:"kind"`
	MediaID            pgtype.UUID        `db:"media_id" json:"media_id"`
	RecordingSessionID pgtype.UUID        `db:"recording_session_id" json:"recording_session_id"`
	RecordingChunkSeq  pgtype.Int4        `db:"recording_chunk_seq" json:"recording_chunk_seq"`
	ReplacesSessionID  pgtype.UUID        `db:"replaces_session_id" json:"replaces_session_id"`
	Bytes              int64              `db:"bytes" json:"bytes"`
	State              string             `db:"state" json:"state"`
	ExpiresAt          pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ReleasedAt         pgtype.Timestamptz `db:"released_at" json:"released_at"`
	CreatedAt          time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt          time.Time          `db:"updated_at" json:"updated_at"`
}
