// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizations = `-- name: CountOrganizations :one
SELECT COUNT(*) FROM organizations
`

func (q *Queries) CountOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug, tier)
VALUES ($1, $2, $3)
RETURNING id, name, slug, settings, encryption_key_id, tier, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name string `db:"name" json:"name"`
	Slug string `db:"slug" json:"slug"`
	Tier string `db:"tier" json:"tier"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug, arg.Tier)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Settings,
		&i.EncryptionKeyID,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganization, id)
	return err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, settings, encryption_key_id, tier, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Settings,
		&i.EncryptionKeyID,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, settings, encryption_key_id, tier, created_at, updated_at FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Settings,
		&i.EncryptionKeyID,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET name = $2, settings = $3, tier = $4
WHERE id = $1
RETURNING id, name, slug, settings, encryption_key_id, tier, created_at, updated_at
`

type UpdateOrganizationParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Name     string      `db:"name" json:"name"`
	Settings []byte      `db:"settings" json:"settings"`
	Tier     string      `db:"tier" json:"tier"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.Settings,
		arg.Tier,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Settings,
		&i.EncryptionKeyID,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationEncryptionKeyID = `-- name: UpdateOrganizationEncryptionKeyID :one
UPDATE organizations
SET encryption_key_id = $2
WHERE id = $1
RETURNING id, name, slug, settings, encryption_key_id, tier, created_at, updated_at
`

type UpdateOrganizationEncryptionKeyIDParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	EncryptionKeyID pgtype.Text `db:"encryption_key_id" json:"encryption_key_id"`
}

func (q *Queries) UpdateOrganizationEncryptionKeyID(ctx context.Context, arg UpdateOrganizationEncryptionKeyIDParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationEncryptionKeyID, arg.ID, arg.EncryptionKeyID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Settings,
		&i.EncryptionKeyID,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
