// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purge.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizationPurgeTargets = `-- name: CountOrganizationPurgeTargets :one
SELECT
    (SELECT COUNT(*) FROM media m WHERE m.organization_id = $1)::bigint AS media,
    (SELECT COUNT(*) FROM transcriptions t WHERE t.organization_id = $1)::bigint AS transcriptions,
    (SELECT COUNT(*) FROM summaries s WHERE s.organization_id = $1)::bigint AS summaries,
    (SELECT COUNT(*) FROM recording_sessions r WHERE r.organization_id = $1)::bigint AS recording_sessions,
    (SELECT COUNT(*) FROM recording_chunks c
        JOIN recording_sessions r ON r.id = c.session_id
        WHERE r.organization_id = $1)::bigint AS recording_chunks,
    (SELECT COUNT(*) FROM mcp_collections c WHERE c.organization_id = $1)::bigint AS collections,
    (SELECT COUNT(*) FROM api_keys k WHERE k.organization_id = $1)::bigint AS api_keys,
    ((SELECT COUNT(*) FROM transcriptions t
        WHERE t.organization_id = $1
          AND t.speechmatics_job_id IS NOT NULL
          AND t.speechmatics_deleted_at IS NULL)
     + (SELECT COUNT(*) FROM transcription_segments s
        JOIN transcriptions t ON t.id = s.transcription_id
        WHERE t.organization_id = $1
          AND s.speechmatics_job_id IS NOT NULL
          AND s.speechmatics_deleted_at IS NULL))::bigint AS pending_provider_deletions
`

type CountOrganizationPurgeTargetsRow struct {
	Media                    int64 `db:"media" json:"media"`
	Transcriptions           int64 `db:"transcriptions" json:"transcriptions"`
	Summaries                int64 `db:"summaries" json:"summaries"`
	RecordingSessions        int64 `db:"recording_sessions" json:"recording_sessions"`
	RecordingChunks          int64 `db:"recording_chunks" json:"recording_chunks"`
	Collections              int64 `db:"collections" json:"collections"`
	ApiKeys                  int64 `db:"api_keys" json:"api_keys"`
	PendingProviderDeletions int64 `db:"pending_provider_deletions" json:"pending_provider_deletions"`
}

func (q *Queries) CountOrganizationPurgeTargets(ctx context.Context, orgID pgtype.UUID) (CountOrganizationPurgeTargetsRow, error) {
	row := q.db.QueryRow(ctx, countOrganizationPurgeTargets, orgID)
	var i CountOrganizationPurgeTargetsRow
	err := row.Scan(
		&i.Media,
		&i.Transcriptions,
		&i.Summaries,
		&i.RecordingSessions,
		&i.RecordingChunks,
		&i.Collections,
		&i.ApiKeys,
		&i.PendingProviderDeletions,
	)
	return i, err
}

const deleteOrganizationAPIKeys = `-- name: DeleteOrganizationAPIKeys :exec
DELETE FROM api_keys WHERE organization_id = $1
`

func (q *Queries) DeleteOrganizationAPIKeys(ctx context.Context, orgID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganizationAPIKeys, orgID)
	return err
}

const deleteOrganizationCollections = `-- name: DeleteOrganizationCollections :exec
DELETE FROM mcp_collections WHERE organization_id = $1
`

func (q *Queries) DeleteOrganizationCollections(ctx context.Context, orgID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganizationCollections, orgID)
	return err
}

const deleteOrganizationForPurge = `-- name: DeleteOrganizationForPurge :execrows
DELETE FROM organizations WHERE id = $1
`

func (q *Queries) DeleteOrganizationForPurge(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrganizationForPurge, orgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOrganizationRecordingSessions = `-- name: DeleteOrganizationRecordingSessions :exec
DELETE FROM recording_sessions WHERE organization_id = $1
`

func (q *Queries) DeleteOrganizationRecordingSessions(ctx context.Context, orgID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganizationRecordingSessions, orgID)
	return err
}

const deleteOrganizationStorageAllocations = `-- name: DeleteOrganizationStorageAllocations :exec
DELETE FROM user_storage_allocations WHERE organization_id = $1
`

func (q *Queries) DeleteOrganizationStorageAllocations(ctx context.Context, orgID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganizationStorageAllocations, orgID)
	return err
}

const getUserOrganizationForPurge = `-- name: GetUserOrganizationForPurge :one

SELECT
    u.id,
    u.organization_id,
    (SELECT COUNT(*) FROM users m WHERE m.organization_id = u.organization_id)::bigint AS member_count
FROM users u
WHERE u.id = $1
`

type GetUserOrganizationForPurgeRow struct {
	ID             string      `db:"id" json:"id"`
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	MemberCount    int64       `db:"member_count" json:"member_count"`
}

// Operator data purge for one person (cmd/server purge-user). Each person has
// a personal organization; these queries only ever address that organization.
func (q *Queries) GetUserOrganizationForPurge(ctx context.Context, userID string) (GetUserOrganizationForPurgeRow, error) {
	row := q.db.QueryRow(ctx, getUserOrganizationForPurge, userID)
	var i GetUserOrganizationForPurgeRow
	err := row.Scan(&i.ID, &i.OrganizationID, &i.MemberCount)
	return i, err
}

const listOrganizationMediaIDsAfter = `-- name: ListOrganizationMediaIDsAfter :many
SELECT id FROM media
WHERE organization_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListOrganizationMediaIDsAfterParams struct {
	OrgID    pgtype.UUID `db:"org_id" json:"org_id"`
	AfterID  pgtype.UUID `db:"after_id" json:"after_id"`
	LimitVal int32       `db:"limit_val" json:"limit_val"`
}

func (q *Queries) ListOrganizationMediaIDsAfter(ctx context.Context, arg ListOrganizationMediaIDsAfterParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listOrganizationMediaIDsAfter, arg.OrgID, arg.AfterID, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scrubOrganizationIdentityForPurge = `-- name: ScrubOrganizationIdentityForPurge :exec
UPDATE organizations SET name = 'Purged workspace', slug = 'purged-' || id::text, settings = '{}'
WHERE id = $1
`

func (q *Queries) ScrubOrganizationIdentityForPurge(ctx context.Context, orgID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, scrubOrganizationIdentityForPurge, orgID)
	return err
}

const scrubOrganizationUsersForPurge = `-- name: ScrubOrganizationUsersForPurge :exec
UPDATE users SET email = '', normalized_email = NULL, name = '', preferences = '{}'
WHERE organization_id = $1
`

func (q *Queries) ScrubOrganizationUsersForPurge(ctx context.Context, orgID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, scrubOrganizationUsersForPurge, orgID)
	return err
}
