// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddMCPCollectionItem(ctx context.Context, arg AddMCPCollectionItemParams) error
	CompleteRecordingSession(ctx context.Context, arg CompleteRecordingSessionParams) (int64, error)
	CountAPIKeysByOrg(ctx context.Context, organizationID pgtype.UUID) (int64, error)
	CountAllUsers(ctx context.Context) (int64, error)
	CountInterruptedRecordingsByUserID(ctx context.Context, userID string) (int64, error)
	CountMediaByOrganization(ctx context.Context, organizationID pgtype.UUID) (int64, error)
	CountOrganizationPurgeTargets(ctx context.Context, orgID pgtype.UUID) (CountOrganizationPurgeTargetsRow, error)
	CountOrganizations(ctx context.Context) (int64, error)
	CountRecordingChunksBySession(ctx context.Context, sessionID pgtype.UUID) (int64, error)
	CountSearchAllEntities(ctx context.Context, arg CountSearchAllEntitiesParams) (int64, error)
	CountSearchMediaByOrganization(ctx context.Context, arg CountSearchMediaByOrganizationParams) (int64, error)
	CountSummariesByOrganization(ctx context.Context, arg CountSummariesByOrganizationParams) (int64, error)
	CountTranscriptionsByOrganization(ctx context.Context, arg CountTranscriptionsByOrganizationParams) (int64, error)
	CountUsersByOrganization(ctx context.Context, organizationID pgtype.UUID) (int64, error)
	CountUsersCreatedSince(ctx context.Context, createdAt time.Time) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateMCPCollection(ctx context.Context, arg CreateMCPCollectionParams) (CreateMCPCollectionRow, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateRecordingChunk(ctx context.Context, arg CreateRecordingChunkParams) (RecordingChunk, error)
	CreateRecordingSession(ctx context.Context, arg CreateRecordingSessionParams) (RecordingSession, error)
	CreateSummary(ctx context.Context, arg CreateSummaryParams) (Summary, error)
	CreateTranscription(ctx context.Context, arg CreateTranscriptionParams) (Transcription, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCollectionItemsByTranscriptionIDs(ctx context.Context, transcriptionIds []pgtype.UUID) error
	DeleteMediaRecordingChunks(ctx context.Context, mediaID pgtype.UUID) error
	DeleteOrganization(ctx context.Context, id pgtype.UUID) error
	DeleteOrganizationAPIKeys(ctx context.Context, orgID pgtype.UUID) error
	DeleteOrganizationCollections(ctx context.Context, orgID pgtype.UUID) error
	DeleteOrganizationForPurge(ctx context.Context, orgID pgtype.UUID) (int64, error)
	DeleteOrganizationRecordingSessions(ctx context.Context, orgID pgtype.UUID) error
	DeleteOrganizationStorageAllocations(ctx context.Context, orgID pgtype.UUID) error
	DeleteRecordingChunksBySession(ctx context.Context, sessionID pgtype.UUID) error
	DeleteUser(ctx context.Context, id string) error
	// Signup anti-abuse: reports whether a provisioned user already occupies an
	// email's normalized alias form (see domain.NormalizeEmailAlias).
	ExistsByNormalizedEmail(ctx context.Context, normalizedEmail pgtype.Text) (bool, error)
	FindStaleRecordingSessions(ctx context.Context, thresholdTime time.Time) ([]RecordingSession, error)
	GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error)
	GetActiveRecordingByUserID(ctx context.Context, userID string) (RecordingSession, error)
	GetActiveSummaryByTranscriptionAndType(ctx context.Context, arg GetActiveSummaryByTranscriptionAndTypeParams) (Summary, error)
	GetDashboardStats(ctx context.Context, organizationID pgtype.UUID) (GetDashboardStatsRow, error)
	GetInterruptedRecordingsByUserID(ctx context.Context, userID string) ([]RecordingSession, error)
	GetMCPCollection(ctx context.Context, arg GetMCPCollectionParams) (GetMCPCollectionRow, error)
	GetMediaByID(ctx context.Context, id pgtype.UUID) (Medium, error)
	GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetRecordingChunkBySessionAndSeq(ctx context.Context, arg GetRecordingChunkBySessionAndSeqParams) (RecordingChunk, error)
	GetRecordingSessionByID(ctx context.Context, id pgtype.UUID) (RecordingSession, error)
	GetSummaryByID(ctx context.Context, id pgtype.UUID) (Summary, error)
	GetTranscriptionByID(ctx context.Context, id pgtype.UUID) (Transcription, error)
	GetTranscriptionByMediaID(ctx context.Context, mediaID pgtype.UUID) (Transcription, error)
	GetTranscriptionBySpeechmaticsJobID(ctx context.Context, speechmaticsJobID pgtype.Text) (Transcription, error)
	// Returns aggregated usage statistics for an organization.
	// Used by GET /api/v1/usage/stats.
	GetUsageStats(ctx context.Context, organizationID pgtype.UUID) (GetUsageStatsRow, error)
	// NOTE: id is the Keycloak subject, not a generated ID
	GetUserByID(ctx context.Context, id string) (User, error)
	// Operator data purge for one person (cmd/server purge-user). Each person has
	// a personal organization; these queries only ever address that organization.
	GetUserOrganizationForPurge(ctx context.Context, userID string) (GetUserOrganizationForPurgeRow, error)
	GetUserPreferences(ctx context.Context, id string) ([]byte, error)
	GetUserWithOrganization(ctx context.Context, id string) (GetUserWithOrganizationRow, error)
	ListAPIKeysByOrg(ctx context.Context, organizationID pgtype.UUID) ([]ApiKey, error)
	ListCompletedTranscriptionsForTranscriptSearch(ctx context.Context, arg ListCompletedTranscriptionsForTranscriptSearchParams) ([]ListCompletedTranscriptionsForTranscriptSearchRow, error)
	ListLiveRecordingAudioRetentionCandidates(ctx context.Context, arg ListLiveRecordingAudioRetentionCandidatesParams) ([]ListLiveRecordingAudioRetentionCandidatesRow, error)
	ListMCPCollectionItems(ctx context.Context, arg ListMCPCollectionItemsParams) ([]ListMCPCollectionItemsRow, error)
	ListMCPCollections(ctx context.Context, arg ListMCPCollectionsParams) ([]ListMCPCollectionsRow, error)
	ListMediaByOrganization(ctx context.Context, arg ListMediaByOrganizationParams) ([]Medium, error)
	ListMediaRecordingChunkKeysForPurge(ctx context.Context, mediaID pgtype.UUID) ([]string, error)
	ListOrganizationMediaIDsAfter(ctx context.Context, arg ListOrganizationMediaIDsAfterParams) ([]pgtype.UUID, error)
	ListRecordingChunksBySession(ctx context.Context, sessionID pgtype.UUID) ([]RecordingChunk, error)
	ListRecordingSessionsByStatusOlderThan(ctx context.Context, arg ListRecordingSessionsByStatusOlderThanParams) ([]RecordingSession, error)
	ListRecordingSessionsWithChunksByStatusOlderThan(ctx context.Context, arg ListRecordingSessionsWithChunksByStatusOlderThanParams) ([]RecordingSession, error)
	ListStaleSubmittedSpeechmatics(ctx context.Context, olderThan time.Time) ([]Transcription, error)
	ListSummariesByOrganization(ctx context.Context, arg ListSummariesByOrganizationParams) ([]ListSummariesByOrganizationRow, error)
	ListSummariesByTranscription(ctx context.Context, transcriptionID pgtype.UUID) ([]ListSummariesByTranscriptionRow, error)
	ListTranscriptionsByOrganization(ctx context.Context, arg ListTranscriptionsByOrganizationParams) ([]ListTranscriptionsByOrganizationRow, error)
	ListTranscriptionsWithoutSummaries(ctx context.Context, arg ListTranscriptionsWithoutSummariesParams) ([]ListTranscriptionsWithoutSummariesRow, error)
	ListUndeletedFromSpeechmatics(ctx context.Context) ([]Transcription, error)
	ListUsersByOrganization(ctx context.Context, arg ListUsersByOrganizationParams) ([]User, error)
	// The media purge runs in one transaction. Rows are locked parent-first
	// (media, then its transcriptions) so a worker that share-locks a
	// transcription before writing segment ciphertext waits for the purge and
	// then sees status 'deleted'.
	LockMediaForPurge(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	LockMediaTranscriptionsForPurge(ctx context.Context, mediaID pgtype.UUID) ([]pgtype.UUID, error)
	LockTranscriptionForPurge(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	MarkMediaAudioDeleted(ctx context.Context, arg MarkMediaAudioDeletedParams) (Medium, error)
	MarkSpeechmaticsDeleted(ctx context.Context, id pgtype.UUID) (int64, error)
	MarkTranscriptionSubmittedToSpeechmatics(ctx context.Context, arg MarkTranscriptionSubmittedToSpeechmaticsParams) (Transcription, error)
	MaxSeqRecordingChunksBySession(ctx context.Context, sessionID pgtype.UUID) (int32, error)
	// PurgeMediaRow keeps a content-free tombstone: status, size, duration and
	// timestamps stay for activity and admin counts; every name, hash, and key
	// reference goes.
	PurgeMediaRow(ctx context.Context, id pgtype.UUID) error
	PurgeSegmentsByTranscriptionIDs(ctx context.Context, transcriptionIds []pgtype.UUID) error
	// The purge queries remove every ciphertext column derived from the listed
	// transcriptions. Provider job ids stay so the Speechmatics cleaner can still
	// delete the provider-side copy of a purged job.
	PurgeSummariesByTranscriptionIDs(ctx context.Context, transcriptionIds []pgtype.UUID) error
	PurgeTranscriptionsByIDs(ctx context.Context, ids []pgtype.UUID) error
	RemoveMCPCollectionItem(ctx context.Context, arg RemoveMCPCollectionItemParams) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
	ScrubMediaRecordingSessions(ctx context.Context, mediaID pgtype.UUID) error
	ScrubOrganizationIdentityForPurge(ctx context.Context, orgID pgtype.UUID) error
	ScrubOrganizationUsersForPurge(ctx context.Context, orgID pgtype.UUID) error
	SearchAllEntities(ctx context.Context, arg SearchAllEntitiesParams) ([]SearchAllEntitiesRow, error)
	SearchMediaByOrganization(ctx context.Context, arg SearchMediaByOrganizationParams) ([]Medium, error)
	SetRecordingCompletedAt(ctx context.Context, arg SetRecordingCompletedAtParams) error
	SetRecordingMediaID(ctx context.Context, arg SetRecordingMediaIDParams) error
	SoftDeleteMedia(ctx context.Context, id pgtype.UUID) error
	SoftDeleteSummariesByMediaID(ctx context.Context, mediaID pgtype.UUID) (int64, error)
	SoftDeleteSummariesByTranscriptionID(ctx context.Context, transcriptionID pgtype.UUID) (int64, error)
	SoftDeleteTranscriptionsByMediaID(ctx context.Context, mediaID pgtype.UUID) (int64, error)
	TotalRecordingChunkPlaintextSizeBySession(ctx context.Context, sessionID pgtype.UUID) (int64, error)
	UndoDeleteSummary(ctx context.Context, arg UndoDeleteSummaryParams) (Summary, error)
	UpdateAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error
	UpdateMediaDuration(ctx context.Context, arg UpdateMediaDurationParams) (Medium, error)
	UpdateMediaEncryption(ctx context.Context, arg UpdateMediaEncryptionParams) (Medium, error)
	UpdateMediaForensics(ctx context.Context, arg UpdateMediaForensicsParams) (Medium, error)
	UpdateMediaMetadata(ctx context.Context, arg UpdateMediaMetadataParams) (Medium, error)
	UpdateMediaScanStatus(ctx context.Context, arg UpdateMediaScanStatusParams) error
	UpdateMediaStatus(ctx context.Context, arg UpdateMediaStatusParams) (Medium, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateOrganizationEncryptionKeyID(ctx context.Context, arg UpdateOrganizationEncryptionKeyIDParams) (Organization, error)
	UpdateRecordingLastActivityAt(ctx context.Context, arg UpdateRecordingLastActivityAtParams) error
	UpdateRecordingLastChunkAt(ctx context.Context, arg UpdateRecordingLastChunkAtParams) error
	UpdateRecordingSessionStatus(ctx context.Context, arg UpdateRecordingSessionStatusParams) (int64, error)
	UpdateSummaryContent(ctx context.Context, arg UpdateSummaryContentParams) (Summary, error)
	UpdateSummaryStatus(ctx context.Context, arg UpdateSummaryStatusParams) (Summary, error)
	UpdateTranscriptionContent(ctx context.Context, arg UpdateTranscriptionContentParams) (Transcription, error)
	UpdateTranscriptionContentCAS(ctx context.Context, arg UpdateTranscriptionContentCASParams) (int64, error)
	UpdateTranscriptionStatus(ctx context.Context, arg UpdateTranscriptionStatusParams) (Transcription, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error
	UpsertRecordingChunk(ctx context.Context, arg UpsertRecordingChunkParams) (RecordingChunk, error)
	UserExistsByID(ctx context.Context, id string) (bool, error)
}

var _ Querier = (*Queries)(nil)
