// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recording.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeRecordingSession = `-- name: CompleteRecordingSession :execrows
UPDATE recording_sessions
SET status = 'completed', completed_at = $1, total_duration = $2
WHERE id = $3 AND status = 'completing'
`

type CompleteRecordingSessionParams struct {
	CompletedAt   pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	TotalDuration float64            `db:"total_duration" json:"total_duration"`
	ID            pgtype.UUID        `db:"id" json:"id"`
}

func (q *Queries) CompleteRecordingSession(ctx context.Context, arg CompleteRecordingSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeRecordingSession, arg.CompletedAt, arg.TotalDuration, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countInterruptedRecordingsByUserID = `-- name: CountInterruptedRecordingsByUserID :one
SELECT COUNT(*) FROM recording_sessions WHERE user_id = $1 AND status = 'interrupted'
`

func (q *Queries) CountInterruptedRecordingsByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countInterruptedRecordingsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecordingChunksBySession = `-- name: CountRecordingChunksBySession :one
SELECT COUNT(*) FROM recording_chunks WHERE session_id = $1
`

func (q *Queries) CountRecordingChunksBySession(ctx context.Context, sessionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecordingChunksBySession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecordingChunk = `-- name: CreateRecordingChunk :one
INSERT INTO recording_chunks (
    session_id, seq, storage_key, wrapped_dek, wrapping_nonce,
    encryption_algo, chunk_size, chunk_count, plaintext_size, checksum
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10
) RETURNING id, session_id, seq, storage_key, wrapped_dek, wrapping_nonce, encryption_algo, chunk_size, chunk_count, plaintext_size, checksum, uploaded_at
`

type CreateRecordingChunkParams struct {
	SessionID      pgtype.UUID `db:"session_id" json:"session_id"`
	Seq            int32       `db:"seq" json:"seq"`
	StorageKey     string      `db:"storage_key" json:"storage_key"`
	WrappedDek     []byte      `db:"wrapped_dek" json:"wrapped_dek"`
	WrappingNonce  []byte      `db:"wrapping_nonce" json:"wrapping_nonce"`
	EncryptionAlgo string      `db:"encryption_algo" json:"encryption_algo"`
	ChunkSize      int32       `db:"chunk_size" json:"chunk_size"`
	ChunkCount     int32       `db:"chunk_count" json:"chunk_count"`
	PlaintextSize  int64       `db:"plaintext_size" json:"plaintext_size"`
	Checksum       string      `db:"checksum" json:"checksum"`
}

func (q *Queries) CreateRecordingChunk(ctx context.Context, arg CreateRecordingChunkParams) (RecordingChunk, error) {
	row := q.db.QueryRow(ctx, createRecordingChunk,
		arg.SessionID,
		arg.Seq,
		arg.StorageKey,
		arg.WrappedDek,
		arg.WrappingNonce,
		arg.EncryptionAlgo,
		arg.ChunkSize,
		arg.ChunkCount,
		arg.PlaintextSize,
		arg.Checksum,
	)
	var i RecordingChunk
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Seq,
		&i.StorageKey,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.EncryptionAlgo,
		&i.ChunkSize,
		&i.ChunkCount,
		&i.PlaintextSize,
		&i.Checksum,
		&i.UploadedAt,
	)
	return i, err
}

const createRecordingSession = `-- name: CreateRecordingSession :one
INSERT INTO recording_sessions (
    organization_id, user_id, status, mime_type, microphone_label, last_activity_at, capture_source
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, organization_id, user_id, status, mime_type, microphone_label, capture_source, media_id, total_duration, last_chunk_at, last_activity_at, created_at, updated_at, completed_at
`

type CreateRecordingSessionParams struct {
	OrganizationID  pgtype.UUID `db:"organization_id" json:"organization_id"`
	UserID          string      `db:"user_id" json:"user_id"`
	Status          string      `db:"status" json:"status"`
	MimeType        string      `db:"mime_type" json:"mime_type"`
	MicrophoneLabel pgtype.Text `db:"microphone_label" json:"microphone_label"`
	LastActivityAt  time.Time   `db:"last_activity_at" json:"last_activity_at"`
	CaptureSource   string      `db:"capture_source" json:"capture_source"`
}

func (q *Queries) CreateRecordingSession(ctx context.Context, arg CreateRecordingSessionParams) (RecordingSession, error) {
	row := q.db.QueryRow(ctx, createRecordingSession,
		arg.OrganizationID,
		arg.UserID,
		arg.Status,
		arg.MimeType,
		arg.MicrophoneLabel,
		arg.LastActivityAt,
		arg.CaptureSource,
	)
	var i RecordingSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.MimeType,
		&i.MicrophoneLabel,
		&i.CaptureSource,
		&i.MediaID,
		&i.TotalDuration,
		&i.LastChunkAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteRecordingChunksBySession = `-- name: DeleteRecordingChunksBySession :exec
DELETE FROM recording_chunks WHERE session_id = $1
`

func (q *Queries) DeleteRecordingChunksBySession(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecordingChunksBySession, sessionID)
	return err
}

const findStaleRecordingSessions = `-- name: FindStaleRecordingSessions :many
SELECT id, organization_id, user_id, status, mime_type, microphone_label, capture_source, media_id, total_duration, last_chunk_at, last_activity_at, created_at, updated_at, completed_at FROM recording_sessions
WHERE status IN ('recording', 'paused') AND last_activity_at < $1
ORDER BY created_at ASC
`

func (q *Queries) FindStaleRecordingSessions(ctx context.Context, thresholdTime time.Time) ([]RecordingSession, error) {
	rows, err := q.db.Query(ctx, findStaleRecordingSessions, thresholdTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecordingSession
	for rows.Next() {
		var i RecordingSession
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Status,
			&i.MimeType,
			&i.MicrophoneLabel,
			&i.CaptureSource,
			&i.MediaID,
			&i.TotalDuration,
			&i.LastChunkAt,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveRecordingByUserID = `-- name: GetActiveRecordingByUserID :one
SELECT id, organization_id, user_id, status, mime_type, microphone_label, capture_source, media_id, total_duration, last_chunk_at, last_activity_at, created_at, updated_at, completed_at FROM recording_sessions
WHERE user_id = $1 AND status IN ('recording', 'paused')
LIMIT 1
`

func (q *Queries) GetActiveRecordingByUserID(ctx context.Context, userID string) (RecordingSession, error) {
	row := q.db.QueryRow(ctx, getActiveRecordingByUserID, userID)
	var i RecordingSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.MimeType,
		&i.MicrophoneLabel,
		&i.CaptureSource,
		&i.MediaID,
		&i.TotalDuration,
		&i.LastChunkAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getInterruptedRecordingsByUserID = `-- name: GetInterruptedRecordingsByUserID :many
SELECT id, organization_id, user_id, status, mime_type, microphone_label, capture_source, media_id, total_duration, last_chunk_at, last_activity_at, created_at, updated_at, completed_at FROM recording_sessions
WHERE user_id = $1 AND status = 'interrupted'
ORDER BY created_at DESC
`

func (q *Queries) GetInterruptedRecordingsByUserID(ctx context.Context, userID string) ([]RecordingSession, error) {
	rows, err := q.db.Query(ctx, getInterruptedRecordingsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecordingSession
	for rows.Next() {
		var i RecordingSession
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Status,
			&i.MimeType,
			&i.MicrophoneLabel,
			&i.CaptureSource,
			&i.MediaID,
			&i.TotalDuration,
			&i.LastChunkAt,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecordingChunkBySessionAndSeq = `-- name: GetRecordingChunkBySessionAndSeq :one
SELECT id, session_id, seq, storage_key, wrapped_dek, wrapping_nonce, encryption_algo, chunk_size, chunk_count, plaintext_size, checksum, uploaded_at FROM recording_chunks WHERE session_id = $1 AND seq = $2
`

type GetRecordingChunkBySessionAndSeqParams struct {
	SessionID pgtype.UUID `db:"session_id" json:"session_id"`
	Seq       int32       `db:"seq" json:"seq"`
}

func (q *Queries) GetRecordingChunkBySessionAndSeq(ctx context.Context, arg GetRecordingChunkBySessionAndSeqParams) (RecordingChunk, error) {
	row := q.db.QueryRow(ctx, getRecordingChunkBySessionAndSeq, arg.SessionID, arg.Seq)
	var i RecordingChunk
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Seq,
		&i.StorageKey,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.EncryptionAlgo,
		&i.ChunkSize,
		&i.ChunkCount,
		&i.PlaintextSize,
		&i.Checksum,
		&i.UploadedAt,
	)
	return i, err
}

const getRecordingSessionByID = `-- name: GetRecordingSessionByID :one
SELECT id, organization_id, user_id, status, mime_type, microphone_label, capture_source, media_id, total_duration, last_chunk_at, last_activity_at, created_at, updated_at, completed_at FROM recording_sessions WHERE id = $1
`

func (q *Queries) GetRecordingSessionByID(ctx context.Context, id pgtype.UUID) (RecordingSession, error) {
	row := q.db.QueryRow(ctx, getRecordingSessionByID, id)
	var i RecordingSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.MimeType,
		&i.MicrophoneLabel,
		&i.CaptureSource,
		&i.MediaID,
		&i.TotalDuration,
		&i.LastChunkAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listLiveRecordingAudioRetentionCandidates = `-- name: ListLiveRecordingAudioRetentionCandidates :many
SELECT rs.id AS session_id, m.id AS media_id, m.organization_id, m.storage_key, rs.completed_at
FROM recording_sessions rs
JOIN media m ON m.id = rs.media_id
JOIN app_recording_retention_policy p ON p.id = TRUE
WHERE p.enabled = TRUE
  AND rs.status = 'completed'
  AND rs.completed_at IS NOT NULL
  AND rs.completed_at <= $1::timestamptz - (p.retention_days::int * INTERVAL '1 day')
  AND (p.apply_to_existing = TRUE OR (p.effective_at IS NOT NULL AND rs.completed_at >= p.effective_at))
  AND rs.media_id IS NOT NULL
  AND m.status != 'deleted'
  AND m.storage_key IS NOT NULL
  AND m.audio_deleted_at IS NULL
ORDER BY rs.completed_at ASC
LIMIT $2
`

type ListLiveRecordingAudioRetentionCandidatesParams struct {
	NowTime  time.Time `db:"now_time" json:"now_time"`
	LimitVal int32     `db:"limit_val" json:"limit_val"`
}

type ListLiveRecordingAudioRetentionCandidatesRow struct {
	SessionID      pgtype.UUID        `db:"session_id" json:"session_id"`
	MediaID        pgtype.UUID        `db:"media_id" json:"media_id"`
	OrganizationID pgtype.UUID        `db:"organization_id" json:"organization_id"`
	StorageKey     pgtype.Text        `db:"storage_key" json:"storage_key"`
	CompletedAt    pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

func (q *Queries) ListLiveRecordingAudioRetentionCandidates(ctx context.Context, arg ListLiveRecordingAudioRetentionCandidatesParams) ([]ListLiveRecordingAudioRetentionCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listLiveRecordingAudioRetentionCandidates, arg.NowTime, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveRecordingAudioRetentionCandidatesRow
	for rows.Next() {
		var i ListLiveRecordingAudioRetentionCandidatesRow
		if err := rows.Scan(
			&i.SessionID,
			&i.MediaID,
			&i.OrganizationID,
			&i.StorageKey,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordingChunksBySession = `-- name: ListRecordingChunksBySession :many
SELECT id, session_id, seq, storage_key, wrapped_dek, wrapping_nonce, encryption_algo, chunk_size, chunk_count, plaintext_size, checksum, uploaded_at FROM recording_chunks WHERE session_id = $1 ORDER BY seq ASC
`

func (q *Queries) ListRecordingChunksBySession(ctx context.Context, sessionID pgtype.UUID) ([]RecordingChunk, error) {
	rows, err := q.db.Query(ctx, listRecordingChunksBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecordingChunk
	for rows.Next() {
		var i RecordingChunk
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Seq,
			&i.StorageKey,
			&i.WrappedDek,
			&i.WrappingNonce,
			&i.EncryptionAlgo,
			&i.ChunkSize,
			&i.ChunkCount,
			&i.PlaintextSize,
			&i.Checksum,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordingSessionsByStatusOlderThan = `-- name: ListRecordingSessionsByStatusOlderThan :many
SELECT id, organization_id, user_id, status, mime_type, microphone_label, capture_source, media_id, total_duration, last_chunk_at, last_activity_at, created_at, updated_at, completed_at FROM recording_sessions
WHERE status = $1 AND updated_at < $2
ORDER BY updated_at ASC
`

type ListRecordingSessionsByStatusOlderThanParams struct {
	Status        string    `db:"status" json:"status"`
	ThresholdTime time.Time `db:"threshold_time" json:"threshold_time"`
}

func (q *Queries) ListRecordingSessionsByStatusOlderThan(ctx context.Context, arg ListRecordingSessionsByStatusOlderThanParams) ([]RecordingSession, error) {
	rows, err := q.db.Query(ctx, listRecordingSessionsByStatusOlderThan, arg.Status, arg.ThresholdTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecordingSession
	for rows.Next() {
		var i RecordingSession
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Status,
			&i.MimeType,
			&i.MicrophoneLabel,
			&i.CaptureSource,
			&i.MediaID,
			&i.TotalDuration,
			&i.LastChunkAt,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordingSessionsWithChunksByStatusOlderThan = `-- name: ListRecordingSessionsWithChunksByStatusOlderThan :many
SELECT rs.id, rs.organization_id, rs.user_id, rs.status, rs.mime_type, rs.microphone_label, rs.capture_source, rs.media_id, rs.total_duration, rs.last_chunk_at, rs.last_activity_at, rs.created_at, rs.updated_at, rs.completed_at FROM recording_sessions rs
WHERE rs.status = $1 AND rs.updated_at < $2
  AND EXISTS (SELECT 1 FROM recording_chunks rc WHERE rc.session_id = rs.id)
ORDER BY rs.updated_at ASC
LIMIT $3
`

type ListRecordingSessionsWithChunksByStatusOlderThanParams struct {
	Status        string    `db:"status" json:"status"`
	ThresholdTime time.Time `db:"threshold_time" json:"threshold_time"`
	LimitVal      int32     `db:"limit_val" json:"limit_val"`
}

func (q *Queries) ListRecordingSessionsWithChunksByStatusOlderThan(ctx context.Context, arg ListRecordingSessionsWithChunksByStatusOlderThanParams) ([]RecordingSession, error) {
	rows, err := q.db.Query(ctx, listRecordingSessionsWithChunksByStatusOlderThan, arg.Status, arg.ThresholdTime, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecordingSession
	for rows.Next() {
		var i RecordingSession
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Status,
			&i.MimeType,
			&i.MicrophoneLabel,
			&i.CaptureSource,
			&i.MediaID,
			&i.TotalDuration,
			&i.LastChunkAt,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxSeqRecordingChunksBySession = `-- name: MaxSeqRecordingChunksBySession :one
SELECT COALESCE(MAX(seq), -1)::integer AS max_seq FROM recording_chunks WHERE session_id = $1
`

func (q *Queries) MaxSeqRecordingChunksBySession(ctx context.Context, sessionID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, maxSeqRecordingChunksBySession, sessionID)
	var max_seq int32
	err := row.Scan(&max_seq)
	return max_seq, err
}

const setRecordingCompletedAt = `-- name: SetRecordingCompletedAt :exec
UPDATE recording_sessions
SET completed_at = $1, total_duration = $2
WHERE id = $3
`

type SetRecordingCompletedAtParams struct {
	CompletedAt   pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	TotalDuration float64            `db:"total_duration" json:"total_duration"`
	ID            pgtype.UUID        `db:"id" json:"id"`
}

func (q *Queries) SetRecordingCompletedAt(ctx context.Context, arg SetRecordingCompletedAtParams) error {
	_, err := q.db.Exec(ctx, setRecordingCompletedAt, arg.CompletedAt, arg.TotalDuration, arg.ID)
	return err
}

const setRecordingMediaID = `-- name: SetRecordingMediaID :exec
UPDATE recording_sessions SET media_id = $1 WHERE id = $2
`

type SetRecordingMediaIDParams struct {
	MediaID pgtype.UUID `db:"media_id" json:"media_id"`
	ID      pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) SetRecordingMediaID(ctx context.Context, arg SetRecordingMediaIDParams) error {
	_, err := q.db.Exec(ctx, setRecordingMediaID, arg.MediaID, arg.ID)
	return err
}

const totalRecordingChunkPlaintextSizeBySession = `-- name: TotalRecordingChunkPlaintextSizeBySession :one
SELECT COALESCE(SUM(plaintext_size), 0)::bigint AS total_plaintext_size
FROM recording_chunks WHERE session_id = $1
`

func (q *Queries) TotalRecordingChunkPlaintextSizeBySession(ctx context.Context, sessionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, totalRecordingChunkPlaintextSizeBySession, sessionID)
	var total_plaintext_size int64
	err := row.Scan(&total_plaintext_size)
	return total_plaintext_size, err
}

const updateRecordingLastActivityAt = `-- name: UpdateRecordingLastActivityAt :exec
UPDATE recording_sessions SET last_activity_at = GREATEST(COALESCE(last_activity_at, $1), $1)
WHERE id = $2
`

type UpdateRecordingLastActivityAtParams struct {
	LastActivityAt time.Time   `db:"last_activity_at" json:"last_activity_at"`
	ID             pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateRecordingLastActivityAt(ctx context.Context, arg UpdateRecordingLastActivityAtParams) error {
	_, err := q.db.Exec(ctx, updateRecordingLastActivityAt, arg.LastActivityAt, arg.ID)
	return err
}

const updateRecordingLastChunkAt = `-- name: UpdateRecordingLastChunkAt :exec
UPDATE recording_sessions SET
    last_chunk_at = GREATEST(COALESCE(last_chunk_at, $1), $1),
    last_activity_at = GREATEST(COALESCE(last_activity_at, $1), $1)
WHERE id = $2
`

type UpdateRecordingLastChunkAtParams struct {
	LastChunkAt pgtype.Timestamptz `db:"last_chunk_at" json:"last_chunk_at"`
	ID          pgtype.UUID        `db:"id" json:"id"`
}

func (q *Queries) UpdateRecordingLastChunkAt(ctx context.Context, arg UpdateRecordingLastChunkAtParams) error {
	_, err := q.db.Exec(ctx, updateRecordingLastChunkAt, arg.LastChunkAt, arg.ID)
	return err
}

const updateRecordingSessionStatus = `-- name: UpdateRecordingSessionStatus :execrows
UPDATE recording_sessions SET status = $1
WHERE id = $2 AND status = $3
`

type UpdateRecordingSessionStatusParams struct {
	NewStatus string      `db:"new_status" json:"new_status"`
	ID        pgtype.UUID `db:"id" json:"id"`
	OldStatus string      `db:"old_status" json:"old_status"`
}

func (q *Queries) UpdateRecordingSessionStatus(ctx context.Context, arg UpdateRecordingSessionStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRecordingSessionStatus, arg.NewStatus, arg.ID, arg.OldStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertRecordingChunk = `-- name: UpsertRecordingChunk :one
INSERT INTO recording_chunks (
    session_id, seq, storage_key, wrapped_dek, wrapping_nonce,
    encryption_algo, chunk_size, chunk_count, plaintext_size, checksum
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10
) ON CONFLICT ON CONSTRAINT uq_recording_chunks_session_seq DO UPDATE SET
    storage_key = EXCLUDED.storage_key,
    wrapped_dek = EXCLUDED.wrapped_dek,
    wrapping_nonce = EXCLUDED.wrapping_nonce,
    encryption_algo = EXCLUDED.encryption_algo,
    chunk_size = EXCLUDED.chunk_size,
    chunk_count = EXCLUDED.chunk_count,
    plaintext_size = EXCLUDED.plaintext_size,
    checksum = EXCLUDED.checksum,
    uploaded_at = now()
RETURNING id, session_id, seq, storage_key, wrapped_dek, wrapping_nonce, encryption_algo, chunk_size, chunk_count, plaintext_size, checksum, uploaded_at
`

type UpsertRecordingChunkParams struct {
	SessionID      pgtype.UUID `db:"session_id" json:"session_id"`
	Seq            int32       `db:"seq" json:"seq"`
	StorageKey     string      `db:"storage_key" json:"storage_key"`
	WrappedDek     []byte      `db:"wrapped_dek" json:"wrapped_dek"`
	WrappingNonce  []byte      `db:"wrapping_nonce" json:"wrapping_nonce"`
	EncryptionAlgo string      `db:"encryption_algo" json:"encryption_algo"`
	ChunkSize      int32       `db:"chunk_size" json:"chunk_size"`
	ChunkCount     int32       `db:"chunk_count" json:"chunk_count"`
	PlaintextSize  int64       `db:"plaintext_size" json:"plaintext_size"`
	Checksum       string      `db:"checksum" json:"checksum"`
}

func (q *Queries) UpsertRecordingChunk(ctx context.Context, arg UpsertRecordingChunkParams) (RecordingChunk, error) {
	row := q.db.QueryRow(ctx, upsertRecordingChunk,
		arg.SessionID,
		arg.Seq,
		arg.StorageKey,
		arg.WrappedDek,
		arg.WrappingNonce,
		arg.EncryptionAlgo,
		arg.ChunkSize,
		arg.ChunkCount,
		arg.PlaintextSize,
		arg.Checksum,
	)
	var i RecordingChunk
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Seq,
		&i.StorageKey,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.EncryptionAlgo,
		&i.ChunkSize,
		&i.ChunkCount,
		&i.PlaintextSize,
		&i.Checksum,
		&i.UploadedAt,
	)
	return i, err
}
