// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: summary.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSummariesByOrganization = `-- name: CountSummariesByOrganization :one
SELECT COUNT(*) FROM summaries s
JOIN transcriptions t ON s.transcription_id = t.id AND t.status != 'deleted'
JOIN media m ON t.media_id = m.id AND m.status != 'deleted'
WHERE s.organization_id = $1 AND s.status != 'deleted'
  AND (
    $2::text = '' OR
    COALESCE(NULLIF(TRIM(m.title), ''), m.filename, '') ILIKE '%' || replace(replace(replace($2::text, '\\', '\\\\'), '%', '\\%'), '_', '\\_') || '%' ESCAPE '\\' OR
    COALESCE(m.description, '') ILIKE '%' || replace(replace(replace($2::text, '\\', '\\\\'), '%', '\\%'), '_', '\\_') || '%' ESCAPE '\\'
  )
`

type CountSummariesByOrganizationParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	Search         string      `db:"search" json:"search"`
}

func (q *Queries) CountSummariesByOrganization(ctx context.Context, arg CountSummariesByOrganizationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSummariesByOrganization, arg.OrganizationID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSummary = `-- name: CreateSummary :one
INSERT INTO summaries (
    organization_id, transcription_id, summary_type, status, high_stakes, review_status,
    summary_profile
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7
) RETURNING id, organization_id, transcription_id, summary_type, summary_profile, status, content_encrypted, content_nonce, wrapped_dek, wrapping_nonce, word_count, prompt_tokens, completion_tokens, thinking_tokens, error_message, high_stakes, review_status, review_findings_encrypted, review_findings_nonce, review_wrapped_dek, review_wrapping_nonce, extraction_encrypted, extraction_nonce, extraction_wrapped_dek, extraction_wrapping_nonce, prompt_version, model, model_metadata, endpoint_location, source_version, source_hash, structured_content_ciphertext, structured_content_nonce, structured_content_wrapped_dek, structured_content_wrapping_nonce, structured_schema_version, degradation_codes, created_at, updated_at, completed_at
`

type CreateSummaryParams struct {
	OrganizationID  pgtype.UUID `db:"organization_id" json:"organization_id"`
	TranscriptionID pgtype.UUID `db:"transcription_id" json:"transcription_id"`
	SummaryType     string      `db:"summary_type" json:"summary_type"`
	Status          string      `db:"status" json:"status"`
	HighStakes      bool        `db:"high_stakes" json:"high_stakes"`
	ReviewStatus    string      `db:"review_status" json:"review_status"`
	SummaryProfile  string      `db:"summary_profile" json:"summary_profile"`
}

func (q *Queries) CreateSummary(ctx context.Context, arg CreateSummaryParams) (Summary, error) {
	row := q.db.QueryRow(ctx, createSummary,
		arg.OrganizationID,
		arg.TranscriptionID,
		arg.SummaryType,
		arg.Status,
		arg.HighStakes,
		arg.ReviewStatus,
		arg.SummaryProfile,
	)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TranscriptionID,
		&i.SummaryType,
		&i.SummaryProfile,
		&i.Status,
		&i.ContentEncrypted,
		&i.ContentNonce,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.WordCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.ThinkingTokens,
		&i.ErrorMessage,
		&i.HighStakes,
		&i.ReviewStatus,
		&i.ReviewFindingsEncrypted,
		&i.ReviewFindingsNonce,
		&i.ReviewWrappedDek,
		&i.ReviewWrappingNonce,
		&i.ExtractionEncrypted,
		&i.ExtractionNonce,
		&i.ExtractionWrappedDek,
		&i.ExtractionWrappingNonce,
		&i.PromptVersion,
		&i.Model,
		&i.ModelMetadata,
		&i.EndpointLocation,
		&i.SourceVersion,
		&i.SourceHash,
		&i.StructuredContentCiphertext,
		&i.StructuredContentNonce,
		&i.StructuredContentWrappedDek,
		&i.StructuredContentWrappingNonce,
		&i.StructuredSchemaVersion,
		&i.DegradationCodes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getActiveSummaryByTranscriptionAndType = `-- name: GetActiveSummaryByTranscriptionAndType :one
SELECT id, organization_id, transcription_id, summary_type, summary_profile, status, content_encrypted, content_nonce, wrapped_dek, wrapping_nonce, word_count, prompt_tokens, completion_tokens, thinking_tokens, error_message, high_stakes, review_status, review_findings_encrypted, review_findings_nonce, review_wrapped_dek, review_wrapping_nonce, extraction_encrypted, extraction_nonce, extraction_wrapped_dek, extraction_wrapping_nonce, prompt_version, model, model_metadata, endpoint_location, source_version, source_hash, structured_content_ciphertext, structured_content_nonce, structured_content_wrapped_dek, structured_content_wrapping_nonce, structured_schema_version, degradation_codes, created_at, updated_at, completed_at FROM summaries
WHERE transcription_id = $1
  AND summary_type = $2
  AND status NOT IN ('failed', 'deleted')
LIMIT 1
`

type GetActiveSummaryByTranscriptionAndTypeParams struct {
	TranscriptionID pgtype.UUID `db:"transcription_id" json:"transcription_id"`
	SummaryType     string      `db:"summary_type" json:"summary_type"`
}

func (q *Queries) GetActiveSummaryByTranscriptionAndType(ctx context.Context, arg GetActiveSummaryByTranscriptionAndTypeParams) (Summary, error) {
	row := q.db.QueryRow(ctx, getActiveSummaryByTranscriptionAndType, arg.TranscriptionID, arg.SummaryType)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TranscriptionID,
		&i.SummaryType,
		&i.SummaryProfile,
		&i.Status,
		&i.ContentEncrypted,
		&i.ContentNonce,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.WordCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.ThinkingTokens,
		&i.ErrorMessage,
		&i.HighStakes,
		&i.ReviewStatus,
		&i.ReviewFindingsEncrypted,
		&i.ReviewFindingsNonce,
		&i.ReviewWrappedDek,
		&i.ReviewWrappingNonce,
		&i.ExtractionEncrypted,
		&i.ExtractionNonce,
		&i.ExtractionWrappedDek,
		&i.ExtractionWrappingNonce,
		&i.PromptVersion,
		&i.Model,
		&i.ModelMetadata,
		&i.EndpointLocation,
		&i.SourceVersion,
		&i.SourceHash,
		&i.StructuredContentCiphertext,
		&i.StructuredContentNonce,
		&i.StructuredContentWrappedDek,
		&i.StructuredContentWrappingNonce,
		&i.StructuredSchemaVersion,
		&i.DegradationCodes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getSummaryByID = `-- name: GetSummaryByID :one
SELECT id, organization_id, transcription_id, summary_type, summary_profile, status, content_encrypted, content_nonce, wrapped_dek, wrapping_nonce, word_count, prompt_tokens, completion_tokens, thinking_tokens, error_message, high_stakes, review_status, review_findings_encrypted, review_findings_nonce, review_wrapped_dek, review_wrapping_nonce, extraction_encrypted, extraction_nonce, extraction_wrapped_dek, extraction_wrapping_nonce, prompt_version, model, model_metadata, endpoint_location, source_version, source_hash, structured_content_ciphertext, structured_content_nonce, structured_content_wrapped_dek, structured_content_wrapping_nonce, structured_schema_version, degradation_codes, created_at, updated_at, completed_at FROM summaries WHERE id = $1
`

func (q *Queries) GetSummaryByID(ctx context.Context, id pgtype.UUID) (Summary, error) {
	row := q.db.QueryRow(ctx, getSummaryByID, id)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TranscriptionID,
		&i.SummaryType,
		&i.SummaryProfile,
		&i.Status,
		&i.ContentEncrypted,
		&i.ContentNonce,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.WordCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.ThinkingTokens,
		&i.ErrorMessage,
		&i.HighStakes,
		&i.ReviewStatus,
		&i.ReviewFindingsEncrypted,
		&i.ReviewFindingsNonce,
		&i.ReviewWrappedDek,
		&i.ReviewWrappingNonce,
		&i.ExtractionEncrypted,
		&i.ExtractionNonce,
		&i.ExtractionWrappedDek,
		&i.ExtractionWrappingNonce,
		&i.PromptVersion,
		&i.Model,
		&i.ModelMetadata,
		&i.EndpointLocation,
		&i.SourceVersion,
		&i.SourceHash,
		&i.StructuredContentCiphertext,
		&i.StructuredContentNonce,
		&i.StructuredContentWrappedDek,
		&i.StructuredContentWrappingNonce,
		&i.StructuredSchemaVersion,
		&i.DegradationCodes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listSummariesByOrganization = `-- name: ListSummariesByOrganization :many
SELECT s.id, s.organization_id, s.transcription_id, s.summary_type, s.summary_profile, s.status, s.content_encrypted, s.content_nonce, s.wrapped_dek, s.wrapping_nonce, s.word_count, s.prompt_tokens, s.completion_tokens, s.thinking_tokens, s.error_message, s.high_stakes, s.review_status, s.review_findings_encrypted, s.review_findings_nonce, s.review_wrapped_dek, s.review_wrapping_nonce, s.extraction_encrypted, s.extraction_nonce, s.extraction_wrapped_dek, s.extraction_wrapping_nonce, s.prompt_version, s.model, s.model_metadata, s.endpoint_location, s.source_version, s.source_hash, s.structured_content_ciphertext, s.structured_content_nonce, s.structured_content_wrapped_dek, s.structured_content_wrapping_nonce, s.structured_schema_version, s.degradation_codes, s.created_at, s.updated_at, s.completed_at, COALESCE(m.filename, '') AS transcription_media_filename,
  COALESCE(NULLIF(TRIM(m.title), ''), m.filename, '') AS transcription_audio_name,
  COALESCE(m.description, '') AS transcription_media_description
FROM summaries s
JOIN transcriptions t ON s.transcription_id = t.id AND t.status != 'deleted'
JOIN media m ON t.media_id = m.id AND m.status != 'deleted'
WHERE s.organization_id = $1 AND s.status != 'deleted'
  AND (
    $2::text = '' OR
    COALESCE(NULLIF(TRIM(m.title), ''), m.filename, '') ILIKE '%' || replace(replace(replace($2::text, '\\', '\\\\'), '%', '\\%'), '_', '\\_') || '%' ESCAPE '\\' OR
    COALESCE(m.description, '') ILIKE '%' || replace(replace(replace($2::text, '\\', '\\\\'), '%', '\\%'), '_', '\\_') || '%' ESCAPE '\\'
  )
ORDER BY s.created_at DESC
LIMIT $4 OFFSET $3
`

type ListSummariesByOrganizationParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	Search         string      `db:"search" json:"search"`
	OffsetVal      int32       `db:"offset_val" json:"offset_val"`
	LimitVal       int32       `db:"limit_val" json:"limit_val"`
}

type ListSummariesByOrganizationRow struct {
	ID                             pgtype.UUID        `db:"id" json:"id"`
	OrganizationID                 pgtype.UUID        `db:"organization_id" json:"organization_id"`
	TranscriptionID                pgtype.UUID        `db:"transcription_id" json:"transcription_id"`
	SummaryType                    string             `db:"summary_type" json:"summary_type"`
	SummaryProfile                 string             `db:"summary_profile" json:"summary_profile"`
	Status                         string             `db:"status" json:"status"`
	ContentEncrypted               []byte             `db:"content_encrypted" json:"content_encrypted"`
	ContentNonce                   []byte             `db:"content_nonce" json:"content_nonce"`
	WrappedDek                     []byte             `db:"wrapped_dek" json:"wrapped_dek"`
	WrappingNonce                  []byte             `db:"wrapping_nonce" json:"wrapping_nonce"`
	WordCount                      int32              `db:"word_count" json:"word_count"`
	PromptTokens                   int32              `db:"prompt_tokens" json:"prompt_tokens"`
	CompletionTokens               int32              `db:"completion_tokens" json:"completion_tokens"`
	ThinkingTokens                 int32              `db:"thinking_tokens" json:"thinking_tokens"`
	ErrorMessage                   pgtype.Text        `db:"error_message" json:"error_message"`
	HighStakes                     bool               `db:"high_stakes" json:"high_stakes"`
	ReviewStatus                   string             `db:"review_status" json:"review_status"`
	ReviewFindingsEncrypted        []byte             `db:"review_findings_encrypted" json:"review_findings_encrypted"`
	ReviewFindingsNonce            []byte             `db:"review_findings_nonce" json:"review_findings_nonce"`
	ReviewWrappedDek               []byte             `db:"review_wrapped_dek" json:"review_wrapped_dek"`
	ReviewWrappingNonce            []byte             `db:"review_wrapping_nonce" json:"review_wrapping_nonce"`
	ExtractionEncrypted            []byte             `db:"extraction_encrypted" json:"extraction_encrypted"`
	ExtractionNonce                []byte             `db:"extraction_nonce" json:"extraction_nonce"`
	ExtractionWrappedDek           []byte             `db:"extraction_wrapped_dek" json:"extraction_wrapped_dek"`
	ExtractionWrappingNonce        []byte             `db:"extraction_wrapping_nonce" json:"extraction_wrapping_nonce"`
	PromptVersion                  pgtype.Text        `db:"prompt_version" json:"prompt_version"`
	Model                          pgtype.Text        `db:"model" json:"model"`
	ModelMetadata                  []byte             `db:"model_metadata" json:"model_metadata"`
	EndpointLocation               pgtype.Text        `db:"endpoint_location" json:"endpoint_location"`
	SourceVersion                  pgtype.Text        `db:"source_version" json:"source_version"`
	SourceHash                     pgtype.Text        `db:"source_hash" json:"source_hash"`
	StructuredContentCiphertext    []byte             `db:"structured_content_ciphertext" json:"structured_content_ciphertext"`
	StructuredContentNonce         []byte             `db:"structured_content_nonce" json:"structured_content_nonce"`
	StructuredContentWrappedDek    []byte             `db:"structured_content_wrapped_dek" json:"structured_content_wrapped_dek"`
	StructuredContentWrappingNonce []byte             `db:"structured_content_wrapping_nonce" json:"structured_content_wrapping_nonce"`
	StructuredSchemaVersion        pgtype.Text        `db:"structured_schema_version" json:"structured_schema_version"`
	DegradationCodes               []string           `db:"degradation_codes" json:"degradation_codes"`
	CreatedAt                      time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt                      time.Time          `db:"updated_at" json:"updated_at"`
	CompletedAt                    pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	TranscriptionMediaFilename     string             `db:"transcription_media_filename" json:"transcription_media_filename"`
	TranscriptionAudioName         string             `db:"transcription_audio_name" json:"transcription_audio_name"`
	TranscriptionMediaDescription  string             `db:"transcription_media_description" json:"transcription_media_description"`
}

func (q *Queries) ListSummariesByOrganization(ctx context.Context, arg ListSummariesByOrganizationParams) ([]ListSummariesByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listSummariesByOrganization,
		arg.OrganizationID,
		arg.Search,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSummariesByOrganizationRow
	for rows.Next() {
		var i ListSummariesByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TranscriptionID,
			&i.SummaryType,
			&i.SummaryProfile,
			&i.Status,
			&i.ContentEncrypted,
			&i.ContentNonce,
			&i.WrappedDek,
			&i.WrappingNonce,
			&i.WordCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.ThinkingTokens,
			&i.ErrorMessage,
			&i.HighStakes,
			&i.ReviewStatus,
			&i.ReviewFindingsEncrypted,
			&i.ReviewFindingsNonce,
			&i.ReviewWrappedDek,
			&i.ReviewWrappingNonce,
			&i.ExtractionEncrypted,
			&i.ExtractionNonce,
			&i.ExtractionWrappedDek,
			&i.ExtractionWrappingNonce,
			&i.PromptVersion,
			&i.Model,
			&i.ModelMetadata,
			&i.EndpointLocation,
			&i.SourceVersion,
			&i.SourceHash,
			&i.StructuredContentCiphertext,
			&i.StructuredContentNonce,
			&i.StructuredContentWrappedDek,
			&i.StructuredContentWrappingNonce,
			&i.StructuredSchemaVersion,
			&i.DegradationCodes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.TranscriptionMediaFilename,
			&i.TranscriptionAudioName,
			&i.TranscriptionMediaDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSummariesByTranscription = `-- name: ListSummariesByTranscription :many
SELECT s.id, s.organization_id, s.transcription_id, s.summary_type, s.summary_profile, s.status, s.content_encrypted, s.content_nonce, s.wrapped_dek, s.wrapping_nonce, s.word_count, s.prompt_tokens, s.completion_tokens, s.thinking_tokens, s.error_message, s.high_stakes, s.review_status, s.review_findings_encrypted, s.review_findings_nonce, s.review_wrapped_dek, s.review_wrapping_nonce, s.extraction_encrypted, s.extraction_nonce, s.extraction_wrapped_dek, s.extraction_wrapping_nonce, s.prompt_version, s.model, s.model_metadata, s.endpoint_location, s.source_version, s.source_hash, s.structured_content_ciphertext, s.structured_content_nonce, s.structured_content_wrapped_dek, s.structured_content_wrapping_nonce, s.structured_schema_version, s.degradation_codes, s.created_at, s.updated_at, s.completed_at, COALESCE(m.filename, '') AS transcription_media_filename,
  COALESCE(NULLIF(TRIM(m.title), ''), m.filename, '') AS transcription_audio_name,
  COALESCE(m.description, '') AS transcription_media_description
FROM summaries s
JOIN transcriptions t ON s.transcription_id = t.id AND t.status != 'deleted'
JOIN media m ON t.media_id = m.id AND m.status != 'deleted'
WHERE s.transcription_id = $1 AND s.status != 'deleted'
ORDER BY s.created_at DESC
`

type ListSummariesByTranscriptionRow struct {
	ID                             pgtype.UUID        `db:"id" json:"id"`
	OrganizationID                 pgtype.UUID        `db:"organization_id" json:"organization_id"`
	TranscriptionID                pgtype.UUID        `db:"transcription_id" json:"transcription_id"`
	SummaryType                    string             `db:"summary_type" json:"summary_type"`
	SummaryProfile                 string             `db:"summary_profile" json:"summary_profile"`
	Status                         string             `db:"status" json:"status"`
	ContentEncrypted               []byte             `db:"content_encrypted" json:"content_encrypted"`
	ContentNonce                   []byte             `db:"content_nonce" json:"content_nonce"`
	WrappedDek                     []byte             `db:"wrapped_dek" json:"wrapped_dek"`
	WrappingNonce                  []byte             `db:"wrapping_nonce" json:"wrapping_nonce"`
	WordCount                      int32              `db:"word_count" json:"word_count"`
	PromptTokens                   int32              `db:"prompt_tokens" json:"prompt_tokens"`
	CompletionTokens               int32              `db:"completion_tokens" json:"completion_tokens"`
	ThinkingTokens                 int32              `db:"thinking_tokens" json:"thinking_tokens"`
	ErrorMessage                   pgtype.Text        `db:"error_message" json:"error_message"`
	HighStakes                     bool               `db:"high_stakes" json:"high_stakes"`
	ReviewStatus                   string             `db:"review_status" json:"review_status"`
	ReviewFindingsEncrypted        []byte             `db:"review_findings_encrypted" json:"review_findings_encrypted"`
	ReviewFindingsNonce            []byte             `db:"review_findings_nonce" json:"review_findings_nonce"`
	ReviewWrappedDek               []byte             `db:"review_wrapped_dek" json:"review_wrapped_dek"`
	ReviewWrappingNonce            []byte             `db:"review_wrapping_nonce" json:"review_wrapping_nonce"`
	ExtractionEncrypted            []byte             `db:"extraction_encrypted" json:"extraction_encrypted"`
	ExtractionNonce                []byte             `db:"extraction_nonce" json:"extraction_nonce"`
	ExtractionWrappedDek           []byte             `db:"extraction_wrapped_dek" json:"extraction_wrapped_dek"`
	ExtractionWrappingNonce        []byte             `db:"extraction_wrapping_nonce" json:"extraction_wrapping_nonce"`
	PromptVersion                  pgtype.Text        `db:"prompt_version" json:"prompt_version"`
	Model                          pgtype.Text        `db:"model" json:"model"`
	ModelMetadata                  []byte             `db:"model_metadata" json:"model_metadata"`
	EndpointLocation               pgtype.Text        `db:"endpoint_location" json:"endpoint_location"`
	SourceVersion                  pgtype.Text        `db:"source_version" json:"source_version"`
	SourceHash                     pgtype.Text        `db:"source_hash" json:"source_hash"`
	StructuredContentCiphertext    []byte             `db:"structured_content_ciphertext" json:"structured_content_ciphertext"`
	StructuredContentNonce         []byte             `db:"structured_content_nonce" json:"structured_content_nonce"`
	StructuredContentWrappedDek    []byte             `db:"structured_content_wrapped_dek" json:"structured_content_wrapped_dek"`
	StructuredContentWrappingNonce []byte             `db:"structured_content_wrapping_nonce" json:"structured_content_wrapping_nonce"`
	StructuredSchemaVersion        pgtype.Text        `db:"structured_schema_version" json:"structured_schema_version"`
	DegradationCodes               []string           `db:"degradation_codes" json:"degradation_codes"`
	CreatedAt                      time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt                      time.Time          `db:"updated_at" json:"updated_at"`
	CompletedAt                    pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	TranscriptionMediaFilename     string             `db:"transcription_media_filename" json:"transcription_media_filename"`
	TranscriptionAudioName         string             `db:"transcription_audio_name" json:"transcription_audio_name"`
	TranscriptionMediaDescription  string             `db:"transcription_media_description" json:"transcription_media_description"`
}

func (q *Queries) ListSummariesByTranscription(ctx context.Context, transcriptionID pgtype.UUID) ([]ListSummariesByTranscriptionRow, error) {
	rows, err := q.db.Query(ctx, listSummariesByTranscription, transcriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSummariesByTranscriptionRow
	for rows.Next() {
		var i ListSummariesByTranscriptionRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TranscriptionID,
			&i.SummaryType,
			&i.SummaryProfile,
			&i.Status,
			&i.ContentEncrypted,
			&i.ContentNonce,
			&i.WrappedDek,
			&i.WrappingNonce,
			&i.WordCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.ThinkingTokens,
			&i.ErrorMessage,
			&i.HighStakes,
			&i.ReviewStatus,
			&i.ReviewFindingsEncrypted,
			&i.ReviewFindingsNonce,
			&i.ReviewWrappedDek,
			&i.ReviewWrappingNonce,
			&i.ExtractionEncrypted,
			&i.ExtractionNonce,
			&i.ExtractionWrappedDek,
			&i.ExtractionWrappingNonce,
			&i.PromptVersion,
			&i.Model,
			&i.ModelMetadata,
			&i.EndpointLocation,
			&i.SourceVersion,
			&i.SourceHash,
			&i.StructuredContentCiphertext,
			&i.StructuredContentNonce,
			&i.StructuredContentWrappedDek,
			&i.StructuredContentWrappingNonce,
			&i.StructuredSchemaVersion,
			&i.DegradationCodes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.TranscriptionMediaFilename,
			&i.TranscriptionAudioName,
			&i.TranscriptionMediaDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSummariesByMediaID = `-- name: SoftDeleteSummariesByMediaID :execrows
UPDATE summaries SET status = 'deleted'
WHERE transcription_id IN (SELECT id FROM transcriptions WHERE media_id = $1)
  AND status != 'deleted'
`

func (q *Queries) SoftDeleteSummariesByMediaID(ctx context.Context, mediaID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteSummariesByMediaID, mediaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteSummariesByTranscriptionID = `-- name: SoftDeleteSummariesByTranscriptionID :execrows
UPDATE summaries SET status = 'deleted'
WHERE transcription_id = $1 AND status != 'deleted'
`

func (q *Queries) SoftDeleteSummariesByTranscriptionID(ctx context.Context, transcriptionID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteSummariesByTranscriptionID, transcriptionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const undoDeleteSummary = `-- name: UndoDeleteSummary :one
UPDATE summaries SET status = $1
WHERE id = $2 AND organization_id = $3 AND status = 'deleted'
RETURNING id, organization_id, transcription_id, summary_type, summary_profile, status, content_encrypted, content_nonce, wrapped_dek, wrapping_nonce, word_count, prompt_tokens, completion_tokens, thinking_tokens, error_message, high_stakes, review_status, review_findings_encrypted, review_findings_nonce, review_wrapped_dek, review_wrapping_nonce, extraction_encrypted, extraction_nonce, extraction_wrapped_dek, extraction_wrapping_nonce, prompt_version, model, model_metadata, endpoint_location, source_version, source_hash, structured_content_ciphertext, structured_content_nonce, structured_content_wrapped_dek, structured_content_wrapping_nonce, structured_schema_version, degradation_codes, created_at, updated_at, completed_at
`

type UndoDeleteSummaryParams struct {
	Status         string      `db:"status" json:"status"`
	ID             pgtype.UUID `db:"id" json:"id"`
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) UndoDeleteSummary(ctx context.Context, arg UndoDeleteSummaryParams) (Summary, error) {
	row := q.db.QueryRow(ctx, undoDeleteSummary, arg.Status, arg.ID, arg.OrganizationID)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TranscriptionID,
		&i.SummaryType,
		&i.SummaryProfile,
		&i.Status,
		&i.ContentEncrypted,
		&i.ContentNonce,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.WordCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.ThinkingTokens,
		&i.ErrorMessage,
		&i.HighStakes,
		&i.ReviewStatus,
		&i.ReviewFindingsEncrypted,
		&i.ReviewFindingsNonce,
		&i.ReviewWrappedDek,
		&i.ReviewWrappingNonce,
		&i.ExtractionEncrypted,
		&i.ExtractionNonce,
		&i.ExtractionWrappedDek,
		&i.ExtractionWrappingNonce,
		&i.PromptVersion,
		&i.Model,
		&i.ModelMetadata,
		&i.EndpointLocation,
		&i.SourceVersion,
		&i.SourceHash,
		&i.StructuredContentCiphertext,
		&i.StructuredContentNonce,
		&i.StructuredContentWrappedDek,
		&i.StructuredContentWrappingNonce,
		&i.StructuredSchemaVersion,
		&i.DegradationCodes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateSummaryContent = `-- name: UpdateSummaryContent :one
UPDATE summaries SET
    status = $1,
    content_encrypted = $2,
    content_nonce = $3,
    wrapped_dek = $4,
    wrapping_nonce = $5,
    word_count = $6,
    prompt_tokens = $7,
    completion_tokens = $8,
    thinking_tokens = $9,
    review_status = $10,
    extraction_encrypted = $11,
    extraction_nonce = $12,
    extraction_wrapped_dek = $13,
    extraction_wrapping_nonce = $14,
    prompt_version = $15,
    model = $16,
    model_metadata = $17,
    endpoint_location = $18,
    source_version = $19,
    source_hash = $20,
    degradation_codes = $21,
    structured_content_ciphertext = $22,
    structured_content_nonce = $23,
    structured_content_wrapped_dek = $24,
    structured_content_wrapping_nonce = $25,
    structured_schema_version = $26,
    completed_at = COALESCE(completed_at, NOW())
WHERE id = $27 AND status NOT IN ('failed', 'deleted')
RETURNING id, organization_id, transcription_id, summary_type, summary_profile, status, content_encrypted, content_nonce, wrapped_dek, wrapping_nonce, word_count, prompt_tokens, completion_tokens, thinking_tokens, error_message, high_stakes, review_status, review_findings_encrypted, review_findings_nonce, review_wrapped_dek, review_wrapping_nonce, extraction_encrypted, extraction_nonce, extraction_wrapped_dek, extraction_wrapping_nonce, prompt_version, model, model_metadata, endpoint_location, source_version, source_hash, structured_content_ciphertext, structured_content_nonce, structured_content_wrapped_dek, structured_content_wrapping_nonce, structured_schema_version, degradation_codes, created_at, updated_at, completed_at
`

type UpdateSummaryContentParams struct {
	Status                         string      `db:"status" json:"status"`
	ContentEncrypted               []byte      `db:"content_encrypted" json:"content_encrypted"`
	ContentNonce                   []byte      `db:"content_nonce" json:"content_nonce"`
	WrappedDek                     []byte      `db:"wrapped_dek" json:"wrapped_dek"`
	WrappingNonce                  []byte      `db:"wrapping_nonce" json:"wrapping_nonce"`
	WordCount                      int32       `db:"word_count" json:"word_count"`
	PromptTokens                   int32       `db:"prompt_tokens" json:"prompt_tokens"`
	CompletionTokens               int32       `db:"completion_tokens" json:"completion_tokens"`
	ThinkingTokens                 int32       `db:"thinking_tokens" json:"thinking_tokens"`
	ReviewStatus                   string      `db:"review_status" json:"review_status"`
	ExtractionEncrypted            []byte      `db:"extraction_encrypted" json:"extraction_encrypted"`
	ExtractionNonce                []byte      `db:"extraction_nonce" json:"extraction_nonce"`
	ExtractionWrappedDek           []byte      `db:"extraction_wrapped_dek" json:"extraction_wrapped_dek"`
	ExtractionWrappingNonce        []byte      `db:"extraction_wrapping_nonce" json:"extraction_wrapping_nonce"`
	PromptVersion                  pgtype.Text `db:"prompt_version" json:"prompt_version"`
	Model                          pgtype.Text `db:"model" json:"model"`
	ModelMetadata                  []byte      `db:"model_metadata" json:"model_metadata"`
	EndpointLocation               pgtype.Text `db:"endpoint_location" json:"endpoint_location"`
	SourceVersion                  pgtype.Text `db:"source_version" json:"source_version"`
	SourceHash                     pgtype.Text `db:"source_hash" json:"source_hash"`
	DegradationCodes               []string    `db:"degradation_codes" json:"degradation_codes"`
	StructuredContentCiphertext    []byte      `db:"structured_content_ciphertext" json:"structured_content_ciphertext"`
	StructuredContentNonce         []byte      `db:"structured_content_nonce" json:"structured_content_nonce"`
	StructuredContentWrappedDek    []byte      `db:"structured_content_wrapped_dek" json:"structured_content_wrapped_dek"`
	StructuredContentWrappingNonce []byte      `db:"structured_content_wrapping_nonce" json:"structured_content_wrapping_nonce"`
	StructuredSchemaVersion        pgtype.Text `db:"structured_schema_version" json:"structured_schema_version"`
	ID                             pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateSummaryContent(ctx context.Context, arg UpdateSummaryContentParams) (Summary, error) {
	row := q.db.QueryRow(ctx, updateSummaryContent,
		arg.Status,
		arg.ContentEncrypted,
		arg.ContentNonce,
		arg.WrappedDek,
		arg.WrappingNonce,
		arg.WordCount,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.ThinkingTokens,
		arg.ReviewStatus,
		arg.ExtractionEncrypted,
		arg.ExtractionNonce,
		arg.ExtractionWrappedDek,
		arg.ExtractionWrappingNonce,
		arg.PromptVersion,
		arg.Model,
		arg.ModelMetadata,
		arg.EndpointLocation,
		arg.SourceVersion,
		arg.SourceHash,
		arg.DegradationCodes,
		arg.StructuredContentCiphertext,
		arg.StructuredContentNonce,
		arg.StructuredContentWrappedDek,
		arg.StructuredContentWrappingNonce,
		arg.StructuredSchemaVersion,
		arg.ID,
	)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TranscriptionID,
		&i.SummaryType,
		&i.SummaryProfile,
		&i.Status,
		&i.ContentEncrypted,
		&i.ContentNonce,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.WordCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.ThinkingTokens,
		&i.ErrorMessage,
		&i.HighStakes,
		&i.ReviewStatus,
		&i.ReviewFindingsEncrypted,
		&i.ReviewFindingsNonce,
		&i.ReviewWrappedDek,
		&i.ReviewWrappingNonce,
		&i.ExtractionEncrypted,
		&i.ExtractionNonce,
		&i.ExtractionWrappedDek,
		&i.ExtractionWrappingNonce,
		&i.PromptVersion,
		&i.Model,
		&i.ModelMetadata,
		&i.EndpointLocation,
		&i.SourceVersion,
		&i.SourceHash,
		&i.StructuredContentCiphertext,
		&i.StructuredContentNonce,
		&i.StructuredContentWrappedDek,
		&i.StructuredContentWrappingNonce,
		&i.StructuredSchemaVersion,
		&i.DegradationCodes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateSummaryStatus = `-- name: UpdateSummaryStatus :one
UPDATE summaries SET status = $1, error_message = COALESCE($2, error_message)
WHERE id = $3 AND (status NOT IN ('completed', 'failed', 'deleted') OR status = $1::text OR $1::text = 'deleted')
RETURNING id, organization_id, transcription_id, summary_type, summary_profile, status, content_encrypted, content_nonce, wrapped_dek, wrapping_nonce, word_count, prompt_tokens, completion_tokens, thinking_tokens, error_message, high_stakes, review_status, review_findings_encrypted, review_findings_nonce, review_wrapped_dek, review_wrapping_nonce, extraction_encrypted, extraction_nonce, extraction_wrapped_dek, extraction_wrapping_nonce, prompt_version, model, model_metadata, endpoint_location, source_version, source_hash, structured_content_ciphertext, structured_content_nonce, structured_content_wrapped_dek, structured_content_wrapping_nonce, structured_schema_version, degradation_codes, created_at, updated_at, completed_at
`

type UpdateSummaryStatusParams struct {
	Status       string      `db:"status" json:"status"`
	ErrorMessage pgtype.Text `db:"error_message" json:"error_message"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateSummaryStatus(ctx context.Context, arg UpdateSummaryStatusParams) (Summary, error) {
	row := q.db.QueryRow(ctx, updateSummaryStatus, arg.Status, arg.ErrorMessage, arg.ID)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TranscriptionID,
		&i.SummaryType,
		&i.SummaryProfile,
		&i.Status,
		&i.ContentEncrypted,
		&i.ContentNonce,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.WordCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.ThinkingTokens,
		&i.ErrorMessage,
		&i.HighStakes,
		&i.ReviewStatus,
		&i.ReviewFindingsEncrypted,
		&i.ReviewFindingsNonce,
		&i.ReviewWrappedDek,
		&i.ReviewWrappingNonce,
		&i.ExtractionEncrypted,
		&i.ExtractionNonce,
		&i.ExtractionWrappedDek,
		&i.ExtractionWrappingNonce,
		&i.PromptVersion,
		&i.Model,
		&i.ModelMetadata,
		&i.EndpointLocation,
		&i.SourceVersion,
		&i.SourceHash,
		&i.StructuredContentCiphertext,
		&i.StructuredContentNonce,
		&i.StructuredContentWrappedDek,
		&i.StructuredContentWrappingNonce,
		&i.StructuredSchemaVersion,
		&i.DegradationCodes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
