// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcription_speechmatics.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTranscriptionBySpeechmaticsJobID = `-- name: GetTranscriptionBySpeechmaticsJobID :one
SELECT id, organization_id, media_id, provider, speechmatics_job_id, speechmatics_deleted_at, status, languages, diarization, expected_speakers, vocabulary_packs, enhance_audio, preprocessor_used, content_encrypted, content_nonce, wrapped_dek, wrapping_nonce, speaker_count, word_count, duration_seconds, error_message, created_at, updated_at, completed_at FROM transcriptions WHERE speechmatics_job_id = $1
`

func (q *Queries) GetTranscriptionBySpeechmaticsJobID(ctx context.Context, speechmaticsJobID pgtype.Text) (Transcription, error) {
	row := q.db.QueryRow(ctx, getTranscriptionBySpeechmaticsJobID, speechmaticsJobID)
	var i Transcription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MediaID,
		&i.Provider,
		&i.SpeechmaticsJobID,
		&i.SpeechmaticsDeletedAt,
		&i.Status,
		&i.Languages,
		&i.Diarization,
		&i.ExpectedSpeakers,
		&i.VocabularyPacks,
		&i.EnhanceAudio,
		&i.PreprocessorUsed,
		&i.ContentEncrypted,
		&i.ContentNonce,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.SpeakerCount,
		&i.WordCount,
		&i.DurationSeconds,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listStaleSubmittedSpeechmatics = `-- name: ListStaleSubmittedSpeechmatics :many
SELECT id, organization_id, media_id, provider, speechmatics_job_id, speechmatics_deleted_at, status, languages, diarization, expected_speakers, vocabulary_packs, enhance_audio, preprocessor_used, content_encrypted, content_nonce, wrapped_dek, wrapping_nonce, speaker_count, word_count, duration_seconds, error_message, created_at, updated_at, completed_at FROM transcriptions
WHERE status = 'submitted'
  AND speechmatics_job_id IS NOT NULL
  AND updated_at < $1
ORDER BY updated_at ASC
LIMIT 50
`

func (q *Queries) ListStaleSubmittedSpeechmatics(ctx context.Context, olderThan time.Time) ([]Transcription, error) {
	rows, err := q.db.Query(ctx, listStaleSubmittedSpeechmatics, olderThan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transcription
	for rows.Next() {
		var i Transcription
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MediaID,
			&i.Provider,
			&i.SpeechmaticsJobID,
			&i.SpeechmaticsDeletedAt,
			&i.Status,
			&i.Languages,
			&i.Diarization,
			&i.ExpectedSpeakers,
			&i.VocabularyPacks,
			&i.EnhanceAudio,
			&i.PreprocessorUsed,
			&i.ContentEncrypted,
			&i.ContentNonce,
			&i.WrappedDek,
			&i.WrappingNonce,
			&i.SpeakerCount,
			&i.WordCount,
			&i.DurationSeconds,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUndeletedFromSpeechmatics = `-- name: ListUndeletedFromSpeechmatics :many
SELECT id, organization_id, media_id, provider, speechmatics_job_id, speechmatics_deleted_at, status, languages, diarization, expected_speakers, vocabulary_packs, enhance_audio, preprocessor_used, content_encrypted, content_nonce, wrapped_dek, wrapping_nonce, speaker_count, word_count, duration_seconds, error_message, created_at, updated_at, completed_at FROM transcriptions
WHERE speechmatics_job_id IS NOT NULL
  AND speechmatics_job_id != ''
  AND speechmatics_deleted_at IS NULL
  AND status IN ('completed', 'failed', 'deleted')
ORDER BY updated_at ASC
LIMIT 50
`

func (q *Queries) ListUndeletedFromSpeechmatics(ctx context.Context) ([]Transcription, error) {
	rows, err := q.db.Query(ctx, listUndeletedFromSpeechmatics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transcription
	for rows.Next() {
		var i Transcription
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MediaID,
			&i.Provider,
			&i.SpeechmaticsJobID,
			&i.SpeechmaticsDeletedAt,
			&i.Status,
			&i.Languages,
			&i.Diarization,
			&i.ExpectedSpeakers,
			&i.VocabularyPacks,
			&i.EnhanceAudio,
			&i.PreprocessorUsed,
			&i.ContentEncrypted,
			&i.ContentNonce,
			&i.WrappedDek,
			&i.WrappingNonce,
			&i.SpeakerCount,
			&i.WordCount,
			&i.DurationSeconds,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSpeechmaticsDeleted = `-- name: MarkSpeechmaticsDeleted :execrows
UPDATE transcriptions SET speechmatics_deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND speechmatics_deleted_at IS NULL
`

func (q *Queries) MarkSpeechmaticsDeleted(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markSpeechmaticsDeleted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markTranscriptionSubmittedToSpeechmatics = `-- name: MarkTranscriptionSubmittedToSpeechmatics :one
UPDATE transcriptions SET
    status = $1,
    provider = 'speechmatics',
    speechmatics_job_id = COALESCE($2, speechmatics_job_id),
    preprocessor_used = COALESCE($3, preprocessor_used)
WHERE id = $4 AND status IN ('pending', 'submitted')
RETURNING id, organization_id, media_id, provider, speechmatics_job_id, speechmatics_deleted_at, status, languages, diarization, expected_speakers, vocabulary_packs, enhance_audio, preprocessor_used, content_encrypted, content_nonce, wrapped_dek, wrapping_nonce, speaker_count, word_count, duration_seconds, error_message, created_at, updated_at, completed_at
`

type MarkTranscriptionSubmittedToSpeechmaticsParams struct {
	Status            string      `db:"status" json:"status"`
	SpeechmaticsJobID pgtype.Text `db:"speechmatics_job_id" json:"speechmatics_job_id"`
	PreprocessorUsed  pgtype.Text `db:"preprocessor_used" json:"preprocessor_used"`
	ID                pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkTranscriptionSubmittedToSpeechmatics(ctx context.Context, arg MarkTranscriptionSubmittedToSpeechmaticsParams) (Transcription, error) {
	row := q.db.QueryRow(ctx, markTranscriptionSubmittedToSpeechmatics,
		arg.Status,
		arg.SpeechmaticsJobID,
		arg.PreprocessorUsed,
		arg.ID,
	)
	var i Transcription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MediaID,
		&i.Provider,
		&i.SpeechmaticsJobID,
		&i.SpeechmaticsDeletedAt,
		&i.Status,
		&i.Languages,
		&i.Diarization,
		&i.ExpectedSpeakers,
		&i.VocabularyPacks,
		&i.EnhanceAudio,
		&i.PreprocessorUsed,
		&i.ContentEncrypted,
		&i.ContentNonce,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.SpeakerCount,
		&i.WordCount,
		&i.DurationSeconds,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
