// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcription.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTranscriptionsByOrganization = `-- name: CountTranscriptionsByOrganization :one
SELECT COUNT(*) FROM transcriptions t
JOIN media m ON t.media_id = m.id AND m.status != 'deleted'
WHERE t.organization_id = $1 AND t.status != 'deleted'
  AND (
    $2::text = '' OR m.title ILIKE '%' || replace(replace(replace($2::text, '\', '\\'), '%', '\%'), '_', '\_') || '%' ESCAPE '\'
    OR m.description ILIKE '%' || replace(replace(replace($2::text, '\', '\\'), '%', '\%'), '_', '\_') || '%' ESCAPE '\'
    OR m.filename ILIKE '%' || replace(replace(replace($2::text, '\', '\\'), '%', '\%'), '_', '\_') || '%' ESCAPE '\'
  )
`

type CountTranscriptionsByOrganizationParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	Search         string      `db:"search" json:"search"`
}

func (q *Queries) CountTranscriptionsByOrganization(ctx context.Context, arg CountTranscriptionsByOrganizationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTranscriptionsByOrganization, arg.OrganizationID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTranscription = `-- name: CreateTranscription :one
INSERT INTO transcriptions (
    organization_id, media_id, languages, diarization, enhance_audio, status,
    vocabulary_packs, expected_speakers
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8
) RETURNING id, organization_id, media_id, provider, speechmatics_job_id, speechmatics_deleted_at, status, languages, diarization, expected_speakers, vocabulary_packs, enhance_audio, preprocessor_used, content_encrypted, content_nonce, wrapped_dek, wrapping_nonce, speaker_count, word_count, duration_seconds, error_message, created_at, updated_at, completed_at
`

type CreateTranscriptionParams struct {
	OrganizationID   pgtype.UUID `db:"organization_id" json:"organization_id"`
	MediaID          pgtype.UUID `db:"media_id" json:"media_id"`
	Languages        []string    `db:"languages" json:"languages"`
	Diarization      bool        `db:"diarization" json:"diarization"`
	EnhanceAudio     bool        `db:"enhance_audio" json:"enhance_audio"`
	Status           string      `db:"status" json:"status"`
	VocabularyPacks  []string    `db:"vocabulary_packs" json:"vocabulary_packs"`
	ExpectedSpeakers pgtype.Int4 `db:"expected_speakers" json:"expected_speakers"`
}

func (q *Queries) CreateTranscription(ctx context.Context, arg CreateTranscriptionParams) (Transcription, error) {
	row := q.db.QueryRow(ctx, createTranscription,
		arg.OrganizationID,
		arg.MediaID,
		arg.Languages,
		arg.Diarization,
		arg.EnhanceAudio,
		arg.Status,
		arg.VocabularyPacks,
		arg.ExpectedSpeakers,
	)
	var i Transcription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MediaID,
		&i.Provider,
		&i.SpeechmaticsJobID,
		&i.SpeechmaticsDeletedAt,
		&i.Status,
		&i.Languages,
		&i.Diarization,
		&i.ExpectedSpeakers,
		&i.VocabularyPacks,
		&i.EnhanceAudio,
		&i.PreprocessorUsed,
		&i.ContentEncrypted,
		&i.ContentNonce,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.SpeakerCount,
		&i.WordCount,
		&i.DurationSeconds,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteCollectionItemsByTranscriptionIDs = `-- name: DeleteCollectionItemsByTranscriptionIDs :exec
DELETE FROM mcp_collection_items WHERE transcription_id = ANY($1::uuid[])
`

func (q *Queries) DeleteCollectionItemsByTranscriptionIDs(ctx context.Context, transcriptionIds []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollectionItemsByTranscriptionIDs, transcriptionIds)
	return err
}

const getTranscriptionByID = `-- name: GetTranscriptionByID :one
SELECT id, organization_id, media_id, provider, speechmatics_job_id, speechmatics_deleted_at, status, languages, diarization, expected_speakers, vocabulary_packs, enhance_audio, preprocessor_used, content_encrypted, content_nonce, wrapped_dek, wrapping_nonce, speaker_count, word_count, duration_seconds, error_message, created_at, updated_at, completed_at FROM transcriptions WHERE id = $1
`

func (q *Queries) GetTranscriptionByID(ctx context.Context, id pgtype.UUID) (Transcription, error) {
	row := q.db.QueryRow(ctx, getTranscriptionByID, id)
	var i Transcription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MediaID,
		&i.Provider,
		&i.SpeechmaticsJobID,
		&i.SpeechmaticsDeletedAt,
		&i.Status,
		&i.Languages,
		&i.Diarization,
		&i.ExpectedSpeakers,
		&i.VocabularyPacks,
		&i.EnhanceAudio,
		&i.PreprocessorUsed,
		&i.ContentEncrypted,
		&i.ContentNonce,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.SpeakerCount,
		&i.WordCount,
		&i.DurationSeconds,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getTranscriptionByMediaID = `-- name: GetTranscriptionByMediaID :one
SELECT id, organization_id, media_id, provider, speechmatics_job_id, speechmatics_deleted_at, status, languages, diarization, expected_speakers, vocabulary_packs, enhance_audio, preprocessor_used, content_encrypted, content_nonce, wrapped_dek, wrapping_nonce, speaker_count, word_count, duration_seconds, error_message, created_at, updated_at, completed_at FROM transcriptions
WHERE media_id = $1 AND status NOT IN ('failed', 'deleted')
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetTranscriptionByMediaID(ctx context.Context, mediaID pgtype.UUID) (Transcription, error) {
	row := q.db.QueryRow(ctx, getTranscriptionByMediaID, mediaID)
	var i Transcription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MediaID,
		&i.Provider,
		&i.SpeechmaticsJobID,
		&i.SpeechmaticsDeletedAt,
		&i.Status,
		&i.Languages,
		&i.Diarization,
		&i.ExpectedSpeakers,
		&i.VocabularyPacks,
		&i.EnhanceAudio,
		&i.PreprocessorUsed,
		&i.ContentEncrypted,
		&i.ContentNonce,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.SpeakerCount,
		&i.WordCount,
		&i.DurationSeconds,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listCompletedTranscriptionsForTranscriptSearch = `-- name: ListCompletedTranscriptionsForTranscriptSearch :many
SELECT t.id, t.organization_id, t.media_id, t.provider, t.speechmatics_job_id, t.speechmatics_deleted_at, t.status, t.languages, t.diarization, t.expected_speakers, t.vocabulary_packs, t.enhance_audio, t.preprocessor_used, t.content_encrypted, t.content_nonce, t.wrapped_dek, t.wrapping_nonce, t.speaker_count, t.word_count, t.duration_seconds, t.error_message, t.created_at, t.updated_at, t.completed_at, m.filename AS media_filename, m.status AS media_status,
       COALESCE(m.title, '') AS media_title, COALESCE(m.description, '') AS media_description
FROM transcriptions t
JOIN media m ON t.media_id = m.id AND m.status != 'deleted'
WHERE t.organization_id = $1
  AND t.status = 'completed'
  AND (
    NOT $2::bool
    OR (t.created_at, t.id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY t.created_at DESC, t.id DESC
LIMIT $5
`

type ListCompletedTranscriptionsForTranscriptSearchParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	HasCursor      bool        `db:"has_cursor" json:"has_cursor"`
	AfterCreatedAt time.Time   `db:"after_created_at" json:"after_created_at"`
	AfterID        pgtype.UUID `db:"after_id" json:"after_id"`
	LimitVal       int32       `db:"limit_val" json:"limit_val"`
}

type ListCompletedTranscriptionsForTranscriptSearchRow struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	OrganizationID        pgtype.UUID        `db:"organization_id" json:"organization_id"`
	MediaID               pgtype.UUID        `db:"media_id" json:"media_id"`
	Provider              string             `db:"provider" json:"provider"`
	SpeechmaticsJobID     pgtype.Text        `db:"speechmatics_job_id" json:"speechmatics_job_id"`
	SpeechmaticsDeletedAt pgtype.Timestamptz `db:"speechmatics_deleted_at" json:"speechmatics_deleted_at"`
	Status                string             `db:"status" json:"status"`
	Languages             []string           `db:"languages" json:"languages"`
	Diarization           bool               `db:"diarization" json:"diarization"`
	ExpectedSpeakers      pgtype.Int4        `db:"expected_speakers" json:"expected_speakers"`
	VocabularyPacks       []string           `db:"vocabulary_packs" json:"vocabulary_packs"`
	EnhanceAudio          bool               `db:"enhance_audio" json:"enhance_audio"`
	PreprocessorUsed      pgtype.Text        `db:"preprocessor_used" json:"preprocessor_used"`
	ContentEncrypted      []byte             `db:"content_encrypted" json:"content_encrypted"`
	ContentNonce          []byte             `db:"content_nonce" json:"content_nonce"`
	WrappedDek            []byte             `db:"wrapped_dek" json:"wrapped_dek"`
	WrappingNonce         []byte             `db:"wrapping_nonce" json:"wrapping_nonce"`
	SpeakerCount          int32              `db:"speaker_count" json:"speaker_count"`
	WordCount             int32              `db:"word_count" json:"word_count"`
	DurationSeconds       float64            `db:"duration_seconds" json:"duration_seconds"`
	ErrorMessage          pgtype.Text        `db:"error_message" json:"error_message"`
	CreatedAt             time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt             time.Time          `db:"updated_at" json:"updated_at"`
	CompletedAt           pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	MediaFilename         string             `db:"media_filename" json:"media_filename"`
	MediaStatus           string             `db:"media_status" json:"media_status"`
	MediaTitle            string             `db:"media_title" json:"media_title"`
	MediaDescription      string             `db:"media_description" json:"media_description"`
}

func (q *Queries) ListCompletedTranscriptionsForTranscriptSearch(ctx context.Context, arg ListCompletedTranscriptionsForTranscriptSearchParams) ([]ListCompletedTranscriptionsForTranscriptSearchRow, error) {
	rows, err := q.db.Query(ctx, listCompletedTranscriptionsForTranscriptSearch,
		arg.OrganizationID,
		arg.HasCursor,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompletedTranscriptionsForTranscriptSearchRow
	for rows.Next() {
		var i ListCompletedTranscriptionsForTranscriptSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MediaID,
			&i.Provider,
			&i.SpeechmaticsJobID,
			&i.SpeechmaticsDeletedAt,
			&i.Status,
			&i.Languages,
			&i.Diarization,
			&i.ExpectedSpeakers,
			&i.VocabularyPacks,
			&i.EnhanceAudio,
			&i.PreprocessorUsed,
			&i.ContentEncrypted,
			&i.ContentNonce,
			&i.WrappedDek,
			&i.WrappingNonce,
			&i.SpeakerCount,
			&i.WordCount,
			&i.DurationSeconds,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.MediaFilename,
			&i.MediaStatus,
			&i.MediaTitle,
			&i.MediaDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptionsByOrganization = `-- name: ListTranscriptionsByOrganization :many
SELECT t.id, t.organization_id, t.media_id, t.provider, t.speechmatics_job_id, t.speechmatics_deleted_at, t.status, t.languages, t.diarization, t.expected_speakers, t.vocabulary_packs, t.enhance_audio, t.preprocessor_used, t.content_encrypted, t.content_nonce, t.wrapped_dek, t.wrapping_nonce, t.speaker_count, t.word_count, t.duration_seconds, t.error_message, t.created_at, t.updated_at, t.completed_at, m.filename AS media_filename, m.status AS media_status,
       COALESCE(m.title, '') AS media_title, COALESCE(m.description, '') AS media_description
FROM transcriptions t
JOIN media m ON t.media_id = m.id AND m.status != 'deleted'
WHERE t.organization_id = $1 AND t.status != 'deleted'
  AND (
    $2::text = '' OR m.title ILIKE '%' || replace(replace(replace($2::text, '\', '\\'), '%', '\%'), '_', '\_') || '%' ESCAPE '\'
    OR m.description ILIKE '%' || replace(replace(replace($2::text, '\', '\\'), '%', '\%'), '_', '\_') || '%' ESCAPE '\'
    OR m.filename ILIKE '%' || replace(replace(replace($2::text, '\', '\\'), '%', '\%'), '_', '\_') || '%' ESCAPE '\'
  )
ORDER BY t.created_at DESC
LIMIT $4 OFFSET $3
`

type ListTranscriptionsByOrganizationParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	Search         string      `db:"search" json:"search"`
	OffsetVal      int32       `db:"offset_val" json:"offset_val"`
	LimitVal       int32       `db:"limit_val" json:"limit_val"`
}

type ListTranscriptionsByOrganizationRow struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	OrganizationID        pgtype.UUID        `db:"organization_id" json:"organization_id"`
	MediaID               pgtype.UUID        `db:"media_id" json:"media_id"`
	Provider              string             `db:"provider" json:"provider"`
	SpeechmaticsJobID     pgtype.Text        `db:"speechmatics_job_id" json:"speechmatics_job_id"`
	SpeechmaticsDeletedAt pgtype.Timestamptz `db:"speechmatics_deleted_at" json:"speechmatics_deleted_at"`
	Status                string             `db:"status" json:"status"`
	Languages             []string           `db:"languages" json:"languages"`
	Diarization           bool               `db:"diarization" json:"diarization"`
	ExpectedSpeakers      pgtype.Int4        `db:"expected_speakers" json:"expected_speakers"`
	VocabularyPacks       []string           `db:"vocabulary_packs" json:"vocabulary_packs"`
	EnhanceAudio          bool               `db:"enhance_audio" json:"enhance_audio"`
	PreprocessorUsed      pgtype.Text        `db:"preprocessor_used" json:"preprocessor_used"`
	ContentEncrypted      []byte             `db:"content_encrypted" json:"content_encrypted"`
	ContentNonce          []byte             `db:"content_nonce" json:"content_nonce"`
	WrappedDek            []byte             `db:"wrapped_dek" json:"wrapped_dek"`
	WrappingNonce         []byte             `db:"wrapping_nonce" json:"wrapping_nonce"`
	SpeakerCount          int32              `db:"speaker_count" json:"speaker_count"`
	WordCount             int32              `db:"word_count" json:"word_count"`
	DurationSeconds       float64            `db:"duration_seconds" json:"duration_seconds"`
	ErrorMessage          pgtype.Text        `db:"error_message" json:"error_message"`
	CreatedAt             time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt             time.Time          `db:"updated_at" json:"updated_at"`
	CompletedAt           pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	MediaFilename         string             `db:"media_filename" json:"media_filename"`
	MediaStatus           string             `db:"media_status" json:"media_status"`
	MediaTitle            string             `db:"media_title" json:"media_title"`
	MediaDescription      string             `db:"media_description" json:"media_description"`
}

func (q *Queries) ListTranscriptionsByOrganization(ctx context.Context, arg ListTranscriptionsByOrganizationParams) ([]ListTranscriptionsByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listTranscriptionsByOrganization,
		arg.OrganizationID,
		arg.Search,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTranscriptionsByOrganizationRow
	for rows.Next() {
		var i ListTranscriptionsByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MediaID,
			&i.Provider,
			&i.SpeechmaticsJobID,
			&i.SpeechmaticsDeletedAt,
			&i.Status,
			&i.Languages,
			&i.Diarization,
			&i.ExpectedSpeakers,
			&i.VocabularyPacks,
			&i.EnhanceAudio,
			&i.PreprocessorUsed,
			&i.ContentEncrypted,
			&i.ContentNonce,
			&i.WrappedDek,
			&i.WrappingNonce,
			&i.SpeakerCount,
			&i.WordCount,
			&i.DurationSeconds,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.MediaFilename,
			&i.MediaStatus,
			&i.MediaTitle,
			&i.MediaDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTranscriptionForPurge = `-- name: LockTranscriptionForPurge :one
SELECT id FROM transcriptions WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockTranscriptionForPurge(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockTranscriptionForPurge, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const purgeSegmentsByTranscriptionIDs = `-- name: PurgeSegmentsByTranscriptionIDs :exec
UPDATE transcription_segments SET
    status = CASE WHEN status IN ('completed', 'failed') THEN status ELSE 'failed' END,
    content_encrypted = NULL,
    content_nonce = NULL,
    wrapped_dek = NULL,
    wrapping_nonce = NULL,
    error_message = NULL
WHERE transcription_id = ANY($1::uuid[])
`

func (q *Queries) PurgeSegmentsByTranscriptionIDs(ctx context.Context, transcriptionIds []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, purgeSegmentsByTranscriptionIDs, transcriptionIds)
	return err
}

const purgeSummariesByTranscriptionIDs = `-- name: PurgeSummariesByTranscriptionIDs :exec

UPDATE summaries SET
    status = 'deleted',
    content_encrypted = NULL,
    content_nonce = NULL,
    wrapped_dek = NULL,
    wrapping_nonce = NULL,
    review_findings_encrypted = NULL,
    review_findings_nonce = NULL,
    review_wrapped_dek = NULL,
    review_wrapping_nonce = NULL,
    extraction_encrypted = NULL,
    extraction_nonce = NULL,
    extraction_wrapped_dek = NULL,
    extraction_wrapping_nonce = NULL,
    structured_content_ciphertext = NULL,
    structured_content_nonce = NULL,
    structured_content_wrapped_dek = NULL,
    structured_content_wrapping_nonce = NULL,
    source_hash = NULL,
    error_message = NULL
WHERE transcription_id = ANY($1::uuid[])
`

// The purge queries remove every ciphertext column derived from the listed
// transcriptions. Provider job ids stay so the Speechmatics cleaner can still
// delete the provider-side copy of a purged job.
func (q *Queries) PurgeSummariesByTranscriptionIDs(ctx context.Context, transcriptionIds []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, purgeSummariesByTranscriptionIDs, transcriptionIds)
	return err
}

const purgeTranscriptionsByIDs = `-- name: PurgeTranscriptionsByIDs :exec
UPDATE transcriptions SET
    status = 'deleted',
    content_encrypted = NULL,
    content_nonce = NULL,
    wrapped_dek = NULL,
    wrapping_nonce = NULL,
    error_message = NULL
WHERE id = ANY($1::uuid[])
`

func (q *Queries) PurgeTranscriptionsByIDs(ctx context.Context, ids []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, purgeTranscriptionsByIDs, ids)
	return err
}

const softDeleteTranscriptionsByMediaID = `-- name: SoftDeleteTranscriptionsByMediaID :execrows
UPDATE transcriptions SET status = 'deleted'
WHERE media_id = $1 AND status != 'deleted'
`

func (q *Queries) SoftDeleteTranscriptionsByMediaID(ctx context.Context, mediaID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTranscriptionsByMediaID, mediaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTranscriptionContent = `-- name: UpdateTranscriptionContent :one
UPDATE transcriptions SET
    status = $1,
    content_encrypted = $2,
    content_nonce = $3,
    wrapped_dek = $4,
    wrapping_nonce = $5,
    speaker_count = $6,
    word_count = $7,
    duration_seconds = $8,
    completed_at = COALESCE(completed_at, NOW())
WHERE id = $9 AND status NOT IN ('failed', 'deleted')
RETURNING id, organization_id, media_id, provider, speechmatics_job_id, speechmatics_deleted_at, status, languages, diarization, expected_speakers, vocabulary_packs, enhance_audio, preprocessor_used, content_encrypted, content_nonce, wrapped_dek, wrapping_nonce, speaker_count, word_count, duration_seconds, error_message, created_at, updated_at, completed_at
`

type UpdateTranscriptionContentParams struct {
	Status           string      `db:"status" json:"status"`
	ContentEncrypted []byte      `db:"content_encrypted" json:"content_encrypted"`
	ContentNonce     []byte      `db:"content_nonce" json:"content_nonce"`
	WrappedDek       []byte      `db:"wrapped_dek" json:"wrapped_dek"`
	WrappingNonce    []byte      `db:"wrapping_nonce" json:"wrapping_nonce"`
	SpeakerCount     int32       `db:"speaker_count" json:"speaker_count"`
	WordCount        int32       `db:"word_count" json:"word_count"`
	DurationSeconds  float64     `db:"duration_seconds" json:"duration_seconds"`
	ID               pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateTranscriptionContent(ctx context.Context, arg UpdateTranscriptionContentParams) (Transcription, error) {
	row := q.db.QueryRow(ctx, updateTranscriptionContent,
		arg.Status,
		arg.ContentEncrypted,
		arg.ContentNonce,
		arg.WrappedDek,
		arg.WrappingNonce,
		arg.SpeakerCount,
		arg.WordCount,
		arg.DurationSeconds,
		arg.ID,
	)
	var i Transcription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MediaID,
		&i.Provider,
		&i.SpeechmaticsJobID,
		&i.SpeechmaticsDeletedAt,
		&i.Status,
		&i.Languages,
		&i.Diarization,
		&i.ExpectedSpeakers,
		&i.VocabularyPacks,
		&i.EnhanceAudio,
		&i.PreprocessorUsed,
		&i.ContentEncrypted,
		&i.ContentNonce,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.SpeakerCount,
		&i.WordCount,
		&i.DurationSeconds,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateTranscriptionContentCAS = `-- name: UpdateTranscriptionContentCAS :execrows
UPDATE transcriptions SET
    content_encrypted = $1,
    content_nonce = $2,
    wrapped_dek = $3,
    wrapping_nonce = $4
WHERE id = $5 AND status = 'completed' AND content_nonce = $6
`

type UpdateTranscriptionContentCASParams struct {
	ContentEncrypted     []byte      `db:"content_encrypted" json:"content_encrypted"`
	ContentNonce         []byte      `db:"content_nonce" json:"content_nonce"`
	WrappedDek           []byte      `db:"wrapped_dek" json:"wrapped_dek"`
	WrappingNonce        []byte      `db:"wrapping_nonce" json:"wrapping_nonce"`
	ID                   pgtype.UUID `db:"id" json:"id"`
	ExpectedContentNonce []byte      `db:"expected_content_nonce" json:"expected_content_nonce"`
}

func (q *Queries) UpdateTranscriptionContentCAS(ctx context.Context, arg UpdateTranscriptionContentCASParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTranscriptionContentCAS,
		arg.ContentEncrypted,
		arg.ContentNonce,
		arg.WrappedDek,
		arg.WrappingNonce,
		arg.ID,
		arg.ExpectedContentNonce,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTranscriptionStatus = `-- name: UpdateTranscriptionStatus :one
UPDATE transcriptions SET
    status = $1,
    error_message = COALESCE($2, error_message),
    preprocessor_used = COALESCE($3, preprocessor_used)
WHERE id = $4 AND (status NOT IN ('completed', 'failed', 'deleted') OR status = $1::text OR $1::text = 'deleted')
RETURNING id, organization_id, media_id, provider, speechmatics_job_id, speechmatics_deleted_at, status, languages, diarization, expected_speakers, vocabulary_packs, enhance_audio, preprocessor_used, content_encrypted, content_nonce, wrapped_dek, wrapping_nonce, speaker_count, word_count, duration_seconds, error_message, created_at, updated_at, completed_at
`

type UpdateTranscriptionStatusParams struct {
	Status           string      `db:"status" json:"status"`
	ErrorMessage     pgtype.Text `db:"error_message" json:"error_message"`
	PreprocessorUsed pgtype.Text `db:"preprocessor_used" json:"preprocessor_used"`
	ID               pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateTranscriptionStatus(ctx context.Context, arg UpdateTranscriptionStatusParams) (Transcription, error) {
	row := q.db.QueryRow(ctx, updateTranscriptionStatus,
		arg.Status,
		arg.ErrorMessage,
		arg.PreprocessorUsed,
		arg.ID,
	)
	var i Transcription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MediaID,
		&i.Provider,
		&i.SpeechmaticsJobID,
		&i.SpeechmaticsDeletedAt,
		&i.Status,
		&i.Languages,
		&i.Diarization,
		&i.ExpectedSpeakers,
		&i.VocabularyPacks,
		&i.EnhanceAudio,
		&i.PreprocessorUsed,
		&i.ContentEncrypted,
		&i.ContentNonce,
		&i.WrappedDek,
		&i.WrappingNonce,
		&i.SpeakerCount,
		&i.WordCount,
		&i.DurationSeconds,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
