// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUsageStats = `-- name: GetUsageStats :one
SELECT
    COALESCE(
        (SELECT SUM(t.duration_seconds) FROM transcriptions t
         WHERE t.organization_id = $1
           AND t.status = 'completed'),
        0
    )::double precision AS total_duration_seconds,

    COALESCE(summary_agg.prompt_tokens, 0)::bigint AS total_prompt_tokens,
    COALESCE(summary_agg.completion_tokens, 0)::bigint AS total_completion_tokens,
    COALESCE(summary_agg.thinking_tokens, 0)::bigint AS total_thinking_tokens,

    (COALESCE(
        (SELECT SUM(m.size) FROM media m
         WHERE m.organization_id = $1
           AND m.status != 'deleted'
           AND m.storage_key IS NOT NULL),
        0
    )
    + COALESCE(
        (SELECT SUM(rc.plaintext_size)
         FROM recording_chunks rc
         JOIN recording_sessions rs ON rs.id = rc.session_id
         WHERE rs.organization_id = $1),
        0
    ))::bigint AS storage_used_bytes,

    COALESCE(
        (SELECT p.enabled FROM app_recording_retention_policy p WHERE p.id = TRUE),
        FALSE
    )::boolean AS live_recording_retention_enabled,
    COALESCE(
        (SELECT p.retention_days FROM app_recording_retention_policy p WHERE p.id = TRUE),
        0
    )::smallint AS live_recording_retention_days

FROM (
    SELECT
        SUM(s.prompt_tokens) AS prompt_tokens,
        SUM(s.completion_tokens) AS completion_tokens,
        SUM(s.thinking_tokens) AS thinking_tokens
    FROM summaries s
    WHERE s.organization_id = $1
      AND s.status = 'completed'
) summary_agg
`

type GetUsageStatsRow struct {
	TotalDurationSeconds          float64 `db:"total_duration_seconds" json:"total_duration_seconds"`
	TotalPromptTokens             int64   `db:"total_prompt_tokens" json:"total_prompt_tokens"`
	TotalCompletionTokens         int64   `db:"total_completion_tokens" json:"total_completion_tokens"`
	TotalThinkingTokens           int64   `db:"total_thinking_tokens" json:"total_thinking_tokens"`
	StorageUsedBytes              int64   `db:"storage_used_bytes" json:"storage_used_bytes"`
	LiveRecordingRetentionEnabled bool    `db:"live_recording_retention_enabled" json:"live_recording_retention_enabled"`
	LiveRecordingRetentionDays    int16   `db:"live_recording_retention_days" json:"live_recording_retention_days"`
}

// Returns aggregated usage statistics for an organization.
// Used by GET /api/v1/usage/stats.
func (q *Queries) GetUsageStats(ctx context.Context, organizationID pgtype.UUID) (GetUsageStatsRow, error) {
	row := q.db.QueryRow(ctx, getUsageStats, organizationID)
	var i GetUsageStatsRow
	err := row.Scan(
		&i.TotalDurationSeconds,
		&i.TotalPromptTokens,
		&i.TotalCompletionTokens,
		&i.TotalThinkingTokens,
		&i.StorageUsedBytes,
		&i.LiveRecordingRetentionEnabled,
		&i.LiveRecordingRetentionDays,
	)
	return i, err
}
