// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllUsers = `-- name: CountAllUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountAllUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByOrganization = `-- name: CountUsersByOrganization :one
SELECT COUNT(*) FROM users WHERE organization_id = $1
`

func (q *Queries) CountUsersByOrganization(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByOrganization, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersCreatedSince = `-- name: CountUsersCreatedSince :one
SELECT COUNT(*) FROM users WHERE created_at >= $1
`

func (q *Queries) CountUsersCreatedSince(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersCreatedSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, organization_id, email, name, normalized_email)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, email, normalized_email, name, role, preferences, created_at, updated_at
`

type CreateUserParams struct {
	ID              string      `db:"id" json:"id"`
	OrganizationID  pgtype.UUID `db:"organization_id" json:"organization_id"`
	Email           string      `db:"email" json:"email"`
	Name            string      `db:"name" json:"name"`
	NormalizedEmail pgtype.Text `db:"normalized_email" json:"normalized_email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.OrganizationID,
		arg.Email,
		arg.Name,
		arg.NormalizedEmail,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.NormalizedEmail,
		&i.Name,
		&i.Role,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const existsByNormalizedEmail = `-- name: ExistsByNormalizedEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE normalized_email = $1)
`

// Signup anti-abuse: reports whether a provisioned user already occupies an
// email's normalized alias form (see domain.NormalizeEmailAlias).
func (q *Queries) ExistsByNormalizedEmail(ctx context.Context, normalizedEmail pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, existsByNormalizedEmail, normalizedEmail)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, organization_id, email, normalized_email, name, role, preferences, created_at, updated_at FROM users WHERE id = $1
`

// NOTE: id is the Keycloak subject, not a generated ID
func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.NormalizedEmail,
		&i.Name,
		&i.Role,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT preferences FROM users WHERE id = $1
`

func (q *Queries) GetUserPreferences(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, id)
	var preferences []byte
	err := row.Scan(&preferences)
	return preferences, err
}

const getUserWithOrganization = `-- name: GetUserWithOrganization :one
SELECT
    u.id,
    u.organization_id,
    u.email,
    u.name,
    u.role,
    u.preferences,
    u.created_at,
    u.updated_at,
    o.id as org_id,
    o.name as org_name,
    o.slug as org_slug,
    o.tier as org_tier,
    o.settings as org_settings,
    o.encryption_key_id as org_encryption_key_id
FROM users u
JOIN organizations o ON u.organization_id = o.id
WHERE u.id = $1
`

type GetUserWithOrganizationRow struct {
	ID                 string      `db:"id" json:"id"`
	OrganizationID     pgtype.UUID `db:"organization_id" json:"organization_id"`
	Email              string      `db:"email" json:"email"`
	Name               string      `db:"name" json:"name"`
	Role               string      `db:"role" json:"role"`
	Preferences        []byte      `db:"preferences" json:"preferences"`
	CreatedAt          time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt          time.Time   `db:"updated_at" json:"updated_at"`
	OrgID              pgtype.UUID `db:"org_id" json:"org_id"`
	OrgName            string      `db:"org_name" json:"org_name"`
	OrgSlug            string      `db:"org_slug" json:"org_slug"`
	OrgTier            string      `db:"org_tier" json:"org_tier"`
	OrgSettings        []byte      `db:"org_settings" json:"org_settings"`
	OrgEncryptionKeyID pgtype.Text `db:"org_encryption_key_id" json:"org_encryption_key_id"`
}

func (q *Queries) GetUserWithOrganization(ctx context.Context, id string) (GetUserWithOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getUserWithOrganization, id)
	var i GetUserWithOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.OrgName,
		&i.OrgSlug,
		&i.OrgTier,
		&i.OrgSettings,
		&i.OrgEncryptionKeyID,
	)
	return i, err
}

const listUsersByOrganization = `-- name: ListUsersByOrganization :many
SELECT id, organization_id, email, normalized_email, name, role, preferences, created_at, updated_at FROM users
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersByOrganizationParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	Limit          int32       `db:"limit" json:"limit"`
	Offset         int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListUsersByOrganization(ctx context.Context, arg ListUsersByOrganizationParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.NormalizedEmail,
			&i.Name,
			&i.Role,
			&i.Preferences,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, name = $3, normalized_email = $4
WHERE id = $1
RETURNING id, organization_id, email, normalized_email, name, role, preferences, created_at, updated_at
`

type UpdateUserParams struct {
	ID              string      `db:"id" json:"id"`
	Email           string      `db:"email" json:"email"`
	Name            string      `db:"name" json:"name"`
	NormalizedEmail pgtype.Text `db:"normalized_email" json:"normalized_email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.NormalizedEmail,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.NormalizedEmail,
		&i.Name,
		&i.Role,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :exec
UPDATE users SET preferences = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserPreferencesParams struct {
	ID          string `db:"id" json:"id"`
	Preferences []byte `db:"preferences" json:"preferences"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, updateUserPreferences, arg.ID, arg.Preferences)
	return err
}

const userExistsByID = `-- name: UserExistsByID :one
SELECT EXISTS(SELECT 1 FROM users WHERE id = $1)
`

func (q *Queries) UserExistsByID(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
